import { useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowRight, Upload, Lock } from "lucide-react";
import { Logo } from "../components/Logo";
import { actions } from "../state/store";
import { CONTENT_STATS } from "../content";

const LOOP = ["Learn", "Understand", "Recall", "Produce", "Speak", "Use", "Retrieve", "Automate"];

export default function Welcome() {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const file = useRef<HTMLInputElement>(null);

  return (
    <div className="welcome">
      <div className="welcome-inner enter">
        <Logo size={36} />
        <div className="stack" style={{ "--gap": "16px", marginTop: 48 } as React.CSSProperties}>
          <h1 className="welcome-title">
            Learn Spanish.
            <br />
            <span className="es welcome-accent">Actually speak it.</span>
          </h1>
          <p className="welcome-sub">Build the Spanish you can use in real life — remembered for the long term, and spoken out loud from your very first session.</p>
        </div>

        <ol className="loop" aria-label="How Habla teaches">
          {LOOP.map((step, i) => (
            <li key={step}>
              <span className="num">{i + 1}</span>
              {step}
            </li>
          ))}
        </ol>

        <div className="stack" style={{ "--gap": "12px", maxWidth: 380 } as React.CSSProperties}>
          <button className="btn btn-primary btn-lg btn-block" onClick={() => navigate("/onboarding")}>
            Get started <ArrowRight size={18} />
          </button>
          <button
            className="btn btn-secondary btn-lg btn-block"
            disabled={loading}
            onClick={async () => {
              setLoading(true);
              await actions.loadDemo();
              navigate("/");
            }}
          >
            {loading ? <span className="spinner" /> : null} Explore a demo learner
          </button>
          <p className="tiny faint">The demo is a learner three weeks in — with real review history, mistakes and progress generated by Habla's learning engine.</p>
          <button className="btn btn-ghost btn-sm" style={{ alignSelf: "flex-start" }} onClick={() => file.current?.click()}>
            <Upload size={15} /> Restore from a backup
          </button>
          <input
            ref={file}
            type="file"
            accept="application/json"
            hidden
            onChange={async (e) => {
              const f = e.target.files?.[0];
              if (!f) return;
              const err = actions.importJson(await f.text());
              if (err) setError(err);
              else navigate("/");
            }}
          />
          {error && <p className="small" style={{ color: "var(--danger-text)" }}>{error}</p>}
        </div>

        <p className="tiny faint row" style={{ gap: 6, marginTop: 40 }}>
          <Lock size={13} /> Your progress is stored on this device. {CONTENT_STATS.lessons} lessons · {CONTENT_STATS.sentences} sentences · {CONTENT_STATS.vocab} words and phrases.
        </p>
      </div>
      <div className="welcome-art" aria-hidden="true">
        <div className="art-card art-1">
          <span className="eyebrow">Speak</span>
          <span className="es" style={{ fontSize: "1.5rem" }}>Hola, me llamo Ana.</span>
          <span className="art-wave">
            {[6, 14, 22, 12, 28, 18, 9, 24, 16, 7, 20, 11].map((h, i) => (
              <i key={i} style={{ height: h }} />
            ))}
          </span>
        </div>
        <div className="art-card art-2">
          <span className="eyebrow">Recall</span>
          <span>I'm hungry.</span>
          <span className="es" style={{ fontSize: "1.3rem" }}>Tengo hambre.</span>
        </div>
        <div className="art-card art-3">
          <span className="eyebrow">Memory</span>
          <span className="art-row">
            <span>Recognition</span>
            <span className="bar thin" style={{ width: 90 }}>
              <span style={{ width: "94%" }} />
            </span>
          </span>
          <span className="art-row">
            <span>Production</span>
            <span className="bar thin accent" style={{ width: 90 }}>
              <span style={{ width: "61%" }} />
            </span>
          </span>
        </div>
      </div>
    </div>
  );
}
