// Grammar taught when it becomes useful: examples first, then the pattern.
// `drills` reference sentences by their Spanish text and are resolved to ids at load time.

import type { Concept } from "../engine/types";

type ConceptDef = Omit<Concept, "drills"> & { drillText: string[] };

export const CONCEPT_DEFS: ConceptDef[] = [
  {
    id: "questions",
    title: "Asking questions",
    remember: "Questions open with ¿ and need no helper verb like “do.”",
    whatChanged: "A statement becomes a question just by changing your tone — and in writing, adding ¿ … ?.",
    why: "Spanish has no “do/does” helper. The verb itself carries the question.",
    how: "Raise your voice at the end. For who/what/where, start with the question word: ¿Dónde…? ¿Qué…?",
    examples: [
      { es: "Hablas español.", en: "You speak Spanish." },
      { es: "¿Hablas español?", en: "Do you speak Spanish?", highlight: "¿Hablas" },
      { es: "¿Dónde está el baño?", en: "Where is the bathroom?", highlight: "Dónde" },
    ],
    drillText: ["¿Hablas español?", "¿Dónde está el baño?", "¿Qué es esto?", "¿Quién es?"],
  },
  {
    id: "pronoun-drop",
    title: "Dropping yo, tú, él",
    remember: "The verb ending already says who — yo and tú are usually optional.",
    whatChanged: "Me llamo Ana and Yo me llamo Ana mean the same thing.",
    why: "Each verb ending points to one person (hablo = I speak), so the pronoun is extra.",
    how: "Leave pronouns out by default. Add them for contrast or emphasis: Yo soy de México, ¿y tú?",
    examples: [
      { es: "Hablo inglés.", en: "I speak English." },
      { es: "Yo hablo inglés, pero ella habla español.", en: "I speak English, but she speaks Spanish.", highlight: "Yo" },
    ],
    drillText: ["Yo me llamo Sofía.", "Hablo inglés y un poco de español.", "Yo también soy de México."],
  },
  {
    id: "ser-identity",
    title: "Ser: who and what you are",
    remember: "Soy, eres, es — for identity, origin and descriptions that define someone.",
    whatChanged: "Ser changes with the person: yo soy, tú eres, él/ella es, nosotros somos, ellos son.",
    why: "Ser is irregular — the forms don't look like the infinitive, so they have to be memorized in use.",
    how: "Use ser for names, where someone is from, jobs and personality: Soy de Chicago. Es muy simpática.",
    examples: [
      { es: "Soy de Estados Unidos.", en: "I'm from the United States.", highlight: "Soy" },
      { es: "¿De dónde eres?", en: "Where are you from?", highlight: "eres" },
      { es: "Mis padres son de Colombia.", en: "My parents are from Colombia.", highlight: "son" },
    ],
    drillText: ["Soy de Estados Unidos.", "¿De dónde eres?", "Ella es de España.", "Mis padres son de Colombia.", "Él es mi amigo.", "La mujer es de México."],
  },
  {
    id: "estar-states",
    title: "Estar: how you are right now",
    remember: "Estoy, estás, está — for feelings, conditions and location.",
    whatChanged: "“I'm fine” is estoy bien, not soy bien.",
    why: "Estar describes states that can change: how you feel today, where something is.",
    how: "Estar + bien / cansado / en casa. Ask ¿Cómo estás? to ask how someone is.",
    examples: [
      { es: "Estoy bien, gracias.", en: "I'm fine, thanks.", highlight: "Estoy" },
      { es: "¿Estás bien?", en: "Are you okay?", highlight: "Estás" },
      { es: "El café está caliente.", en: "The coffee is hot.", highlight: "está" },
    ],
    drillText: ["Estoy bien, gracias.", "Sí, estoy cansado.", "¿Estás bien?", "No estoy mal.", "Estoy muy bien."],
  },
  {
    id: "ser-estar",
    title: "Ser vs. estar",
    remember: "“Estoy” is used for temporary states and locations; “soy” for who you are.",
    whatChanged: "Soy alto (I'm tall) but estoy cansado (I'm tired). Soy de Chicago but estoy en Madrid.",
    why: "Ser = what something is. Estar = how or where it is right now.",
    how: "Ask yourself: is it identity, origin or a lasting trait? → ser. Feeling, condition or location? → estar.",
    examples: [
      { es: "Soy alto.", en: "I'm tall.", highlight: "Soy" },
      { es: "Estoy cansado.", en: "I'm tired.", highlight: "Estoy" },
      { es: "Soy de Chicago, pero estoy en Madrid.", en: "I'm from Chicago, but I'm in Madrid.", highlight: "estoy" },
    ],
    drillText: ["Estoy cansado.", "Soy alto.", "Estamos en casa.", "Mi madre es muy joven.", "Ella está triste hoy.", "Soy de Chicago, pero estoy en Madrid.", "Hoy estoy muy ocupada.", "El supermercado está cerca."],
  },
  {
    id: "gender",
    title: "Masculine and feminine",
    remember: "Articles and adjectives match the noun: el chico simpático, la chica simpática.",
    whatChanged: "Amigo → amiga, simpático → simpática, el → la, un → una.",
    why: "Every Spanish noun has a gender, and the words around it agree with it.",
    how: "Learn nouns with their article (la casa, el libro). Then make adjectives match: la casa pequeña.",
    examples: [
      { es: "El chico es simpático.", en: "The boy is nice.", highlight: "simpático" },
      { es: "La chica es simpática.", en: "The girl is nice.", highlight: "simpática" },
      { es: "Quiero la camisa roja.", en: "I want the red shirt.", highlight: "roja" },
    ],
    drillText: ["Ella es mi amiga.", "La chica es simpática.", "Quiero la camisa roja.", "Vivo en una casa pequeña.", "Tengo mucha hambre.", "Esta camisa es muy bonita."],
  },
  {
    id: "possessives",
    title: "My, your: mi, tu",
    remember: "Mi and tu add -s before plural nouns: mis padres, tus amigos.",
    whatChanged: "Mi madre, but mis padres.",
    why: "Possessives agree in number with the thing owned, not the owner.",
    how: "Mi/tu + singular noun; mis/tus + plural noun. Tu (your) has no accent; tú (you) does.",
    examples: [
      { es: "Mi madre se llama Rosa.", en: "My mother's name is Rosa.", highlight: "Mi" },
      { es: "Mis padres son de Colombia.", en: "My parents are from Colombia.", highlight: "Mis" },
    ],
    drillText: ["Mi madre se llama Rosa.", "Mis padres son de Colombia.", "¿Cómo se llama tu padre?"],
  },
  {
    id: "tener-expressions",
    title: "Tener for hunger, thirst and age",
    remember: "Spanish “has” hunger and years: tengo hambre, tengo veinte años.",
    whatChanged: "“I am hungry” is tengo hambre — not estoy hambre.",
    why: "Hambre, sed and años are nouns in Spanish. You have them.",
    how: "Tener + hambre / sed / frío / calor / … años. Use mucha hambre (hambre is feminine).",
    examples: [
      { es: "Tengo hambre.", en: "I'm hungry.", highlight: "Tengo" },
      { es: "¿Tienes sed?", en: "Are you thirsty?", highlight: "Tienes" },
      { es: "Tengo veinte años.", en: "I'm twenty.", highlight: "Tengo" },
    ],
    drillText: ["Tengo hambre.", "¿Tienes hambre?", "Tengo mucha hambre.", "No tengo hambre.", "Tengo sed.", "Tengo veinte años.", "¿Cuántos años tienes?", "Mi padre tiene cincuenta años."],
  },
  {
    id: "stem-changing",
    title: "Verbs that change inside",
    remember: "Some verbs change their stem: quiero, puedo, cuesta — but not with nosotros.",
    whatChanged: "Querer → quiero, poder → puedo, costar → cuesta, almorzar → almuerzo.",
    why: "When the stress falls on the stem, e becomes ie and o becomes ue.",
    how: "Change the stem for yo, tú, él and ellos. Keep it for nosotros: queremos, podemos.",
    examples: [
      { es: "Quiero comer.", en: "I want to eat.", highlight: "Quiero" },
      { es: "¿Puedo pagar con tarjeta?", en: "Can I pay by card?", highlight: "Puedo" },
      { es: "¿Cuánto cuesta?", en: "How much is it?", highlight: "cuesta" },
    ],
    drillText: ["Quiero comer.", "¿Quieres comer?", "¿Puedo pagar con tarjeta?", "¿Cuánto cuesta?", "Almuerzo a la una.", "Prefiero el café."],
  },
  {
    id: "gustar",
    title: "Gustar: how “liking” works",
    remember: "Me gusta + one thing, me gustan + several things.",
    whatChanged: "“I like apples” is me gustan las manzanas — the apples do the pleasing.",
    why: "Gustar means “to be pleasing.” The thing you like is the subject, so the verb matches it.",
    how: "Me / te / le + gusta + singular or infinitive; gustan + plural. Never “yo gusto.”",
    examples: [
      { es: "Me gusta el pollo.", en: "I like chicken.", highlight: "gusta" },
      { es: "Me gustan las manzanas.", en: "I like apples.", highlight: "gustan" },
      { es: "¿Te gusta la fruta?", en: "Do you like fruit?", highlight: "Te gusta" },
    ],
    drillText: ["Me gusta el pollo.", "Me gustan las manzanas.", "¿Te gusta la fruta?", "No me gusta el queso.", "Me gustan los zapatos blancos."],
  },
  {
    id: "present-regular",
    title: "Present tense: -ar, -er, -ir",
    remember: "Drop the ending and add who: hablo, hablas, habla; como, comes, come; vivo, vives, vive.",
    whatChanged: "Trabajar → trabajo (I work), vivir → vivo (I live), leer → leo (I read).",
    why: "The ending tells you who is doing the action.",
    how: "-ar: o, as, a, amos, an. -er: o, es, e, emos, en. -ir: o, es, e, imos, en.",
    examples: [
      { es: "Trabajo en una oficina.", en: "I work in an office.", highlight: "Trabajo" },
      { es: "¿Dónde vives?", en: "Where do you live?", highlight: "vives" },
      { es: "Mi hermano estudia en la universidad.", en: "My brother studies at the university.", highlight: "estudia" },
    ],
    drillText: ["Trabajo en una oficina.", "Estudio español todos los días.", "¿Dónde vives?", "Vivo en una casa pequeña.", "Leo un libro.", "Ella escribe en español."],
  },
  {
    id: "telling-time",
    title: "Telling the time",
    remember: "Es la una, but son las dos, son las tres… At a time = a las.",
    whatChanged: "One o'clock is singular (es la una); every other hour is plural (son las…).",
    why: "The article agrees with horas (hours), which is feminine: la una, las dos.",
    how: "Add y media (half past), y cuarto (quarter past), de la mañana / tarde / noche.",
    examples: [
      { es: "Es la una.", en: "It's one o'clock.", highlight: "Es la" },
      { es: "Son las tres y media.", en: "It's three thirty.", highlight: "Son las" },
      { es: "Como a las dos de la tarde.", en: "I eat at two p.m.", highlight: "a las" },
    ],
    drillText: ["¿Qué hora es?", "Es la una.", "Son las tres y media.", "Son las ocho de la mañana.", "Como a las dos de la tarde."],
  },
  {
    id: "reflexive",
    title: "Reflexive verbs: me levanto",
    remember: "Me / te / se go before the verb when you do something to yourself.",
    whatChanged: "Levantarse → me levanto (I get [myself] up), te levantas, se levanta.",
    why: "Many routine verbs are “done to yourself” in Spanish.",
    how: "Move the -se to the front and match it: me (yo), te (tú), se (él/ella), nos (nosotros).",
    examples: [
      { es: "Me levanto a las siete.", en: "I get up at seven.", highlight: "Me levanto" },
      { es: "¿A qué hora te levantas?", en: "What time do you get up?", highlight: "te levantas" },
    ],
    drillText: ["Me levanto a las siete.", "Primero me ducho y después desayuno.", "Me acuesto tarde.", "¿A qué hora te levantas?"],
  },
  {
    id: "hay-esta",
    title: "Hay vs. está",
    remember: "Hay = there is (does it exist?). Está = is located (where is this one?).",
    whatChanged: "¿Hay un banco cerca? but ¿Dónde está el banco?",
    why: "Hay introduces something new; está locates something you already know about.",
    how: "Hay + un/una/number. Está + el/la/mi.",
    examples: [
      { es: "¿Hay un banco cerca?", en: "Is there a bank nearby?", highlight: "Hay" },
      { es: "El supermercado está cerca.", en: "The supermarket is close.", highlight: "está" },
    ],
    drillText: ["¿Hay un banco cerca?", "El supermercado está cerca.", "Hay un parque muy bonito.", "El hotel está en el centro.", "¿Hay un baño?"],
  },
  {
    id: "al-del",
    title: "Al and del",
    remember: "a + el = al; de + el = del. Never “a el” or “de el.”",
    whatChanged: "Voy al museo; está al lado del hotel.",
    why: "Spanish merges these very common pairs to make speech smoother.",
    how: "Only with el (masculine singular): a la playa stays a la.",
    examples: [
      { es: "¿Cómo llego al museo?", en: "How do I get to the museum?", highlight: "al" },
      { es: "El banco está al lado del hotel.", en: "The bank is next to the hotel.", highlight: "del" },
    ],
    drillText: ["¿Cómo llego al museo?", "Voy al trabajo en metro.", "El banco está al lado del hotel.", "Ayer fui al cine."],
  },
  {
    id: "ir-a",
    title: "Going to: voy a + verb",
    remember: "Voy a + infinitive = I'm going to do something. Don't drop the a.",
    whatChanged: "Voy a comer (I'm going to eat). Mañana voy a ir (I'm going to go).",
    why: "It's the easiest way to talk about the future — you only need ir and an infinitive.",
    how: "voy / vas / va / vamos / van + a + infinitive.",
    examples: [
      { es: "Voy a comer con mi amiga.", en: "I'm going to eat with my friend.", highlight: "Voy a" },
      { es: "¿Qué vas a hacer esta noche?", en: "What are you going to do tonight?", highlight: "vas a" },
      { es: "Mañana voy a ir al supermercado.", en: "Tomorrow I'm going to go to the supermarket.", highlight: "voy a ir" },
    ],
    drillText: ["Mañana voy a ir al supermercado.", "Voy a comer con mi amiga.", "¿Qué vas a hacer esta noche?", "Vamos a visitar el museo.", "El tren va a llegar tarde."],
  },
  {
    id: "preterite",
    title: "The past: what happened",
    remember: "-ar → -é, -er/-ir → -í for “I.” Ir and ser share fui.",
    whatChanged: "Como (I eat) → comí (I ate). Trabajo → trabajé. Voy → fui.",
    why: "The preterite is for finished actions: yesterday, last week, once.",
    how: "Yo: -é / -í. Tú: -aste / -iste. Él: -ó / -ió. Key irregulars: fui, hice, vi.",
    examples: [
      { es: "Ayer comí pizza.", en: "Yesterday I ate pizza.", highlight: "comí" },
      { es: "Ayer fui al cine.", en: "Yesterday I went to the movies.", highlight: "fui" },
      { es: "Trabajé todo el día.", en: "I worked all day.", highlight: "Trabajé" },
    ],
    drillText: ["Ayer comí pizza.", "Ayer fui al cine.", "Anoche vi una película.", "¿Qué comiste ayer?", "Trabajé todo el día.", "Hablé con mi madre.", "¿Qué hiciste el fin de semana?", "Llegué a casa tarde."],
  },
  {
    id: "tener-que",
    title: "Have to: tener que",
    remember: "Tengo que + infinitive = I have to.",
    whatChanged: "Tengo que trabajar (I have to work).",
    why: "Tener que expresses obligation — it's the most common way to say “must.”",
    how: "tengo / tienes / tiene / tenemos / tienen + que + infinitive.",
    examples: [
      { es: "Tengo que trabajar mañana.", en: "I have to work tomorrow.", highlight: "Tengo que" },
      { es: "Tenemos que llegar temprano.", en: "We have to arrive early.", highlight: "Tenemos que" },
    ],
    drillText: ["Tengo que trabajar mañana.", "Tenemos que llegar temprano."],
  },
  {
    id: "opinions",
    title: "Giving opinions",
    remember: "Creo que… / Me parece… / (No) estoy de acuerdo.",
    whatChanged: "“I think it's good” is creo que es bueno — que is required.",
    why: "Spanish can't drop “that” the way English does.",
    how: "Creo que + full sentence. Me parece + adjective. Agreeing uses estar.",
    examples: [
      { es: "Creo que es una buena idea.", en: "I think it's a good idea.", highlight: "Creo que" },
      { es: "No estoy de acuerdo.", en: "I don't agree.", highlight: "estoy de acuerdo" },
    ],
    drillText: ["Creo que es una buena idea.", "Me parece interesante.", "No estoy de acuerdo.", "Creo que sí."],
  },
  {
    id: "comparisons",
    title: "Comparing: más … que",
    remember: "Más + adjective + que = -er than. Mejor = better, peor = worse.",
    whatChanged: "Madrid es más grande que Sevilla.",
    why: "Spanish doesn't add -er to adjectives; it uses más.",
    how: "más / menos + adjective + que. Irregular: mejor, peor.",
    examples: [
      { es: "Madrid es más grande que Sevilla.", en: "Madrid is bigger than Seville.", highlight: "más grande que" },
      { es: "El té es mejor que el café.", en: "Tea is better than coffee.", highlight: "mejor que" },
    ],
    drillText: ["Madrid es más grande que Sevilla.", "El té es mejor que el café.", "Esta película es peor."],
  },
  {
    id: "por-para",
    title: "Por vs. para",
    remember: "Para = for (a purpose, a person, a deadline). Por = through, per, because of.",
    whatChanged: "Una mesa para dos, but dos veces por semana.",
    why: "English uses “for” for both ideas; Spanish splits them.",
    how: "Para + destination, recipient or goal. Por + exchange, frequency, or por favor.",
    examples: [
      { es: "Una mesa para dos, por favor.", en: "A table for two, please.", highlight: "para" },
      { es: "¿Tienes planes para el sábado?", en: "Do you have plans for Saturday?", highlight: "para" },
    ],
    drillText: ["Una mesa para dos, por favor.", "¿Tienes planes para el sábado?", "A veces cocino para mis amigos.", "Para mí, el pollo con arroz."],
  },
  {
    id: "accents",
    title: "Accents and ñ",
    remember: "Accents change meaning: tú (you) vs. tu (your); mañana has ñ, not n.",
    whatChanged: "Trabajé (I worked) and trabaje are different words.",
    why: "The accent marks which syllable is stressed — and sometimes it's the only difference.",
    how: "On a keyboard without Spanish keys, use the accent buttons under the answer box.",
    examples: [
      { es: "Mañana voy a ir al supermercado.", en: "Tomorrow I'm going to go to the supermarket.", highlight: "Mañana" },
      { es: "¿Y tú?", en: "And you?", highlight: "tú" },
    ],
    drillText: ["Mañana voy a ir al supermercado.", "¿Dónde está el baño?", "Trabajé todo el día.", "¿Cómo estás?"],
  },
  {
    id: "word-order",
    title: "Word order",
    remember: "Adjectives usually go after the noun; no goes right before the verb.",
    whatChanged: "Una casa pequeña (a small house). No me gusta (I don't like).",
    why: "Spanish puts the describing word after the thing it describes.",
    how: "Noun + adjective. No + (pronoun) + verb.",
    examples: [
      { es: "Vivo en una casa pequeña.", en: "I live in a small house.", highlight: "casa pequeña" },
      { es: "No me gusta el queso.", en: "I don't like cheese.", highlight: "No me gusta" },
    ],
    drillText: ["Vivo en una casa pequeña.", "No me gusta el queso.", "Busco una camisa azul.", "Quiero agua fría."],
  },
];
