// Level 1 — Foundations (approx. A1).
// Every lesson teaches vocabulary inside sentences and ends with speaking.

import type { UnitDef } from "./build";

export const LEVEL1: UnitDef[] = [
  // ─── Unit 1 ────────────────────────────────────────────────────────────
  {
    title: "First Conversations",
    description: "Greet people, introduce yourself and ask simple questions.",
    canDo: ["Say hello and goodbye", "Introduce yourself", "Say where you're from", "Ask how someone is"],
    lessons: [
      {
        title: "Hello",
        titleEs: "Hola",
        goal: "Greet someone at any time of day and say goodbye.",
        minutes: 5,
        vocab: [
          ["hola", "hello", "interjection", { emoji: "👋", freq: 40, def: "lo que dices cuando ves a alguien", alt: ["hi"] }],
          ["buenos días", "good morning", "phrase", { freq: 120, emoji: "🌅", def: "saludo para la mañana" }],
          ["buenas tardes", "good afternoon", "phrase", { freq: 180, def: "saludo para la tarde" }],
          ["buenas noches", "good night / good evening", "phrase", { freq: 190, emoji: "🌙", alt: ["good evening", "good night"] }],
          ["adiós", "goodbye", "interjection", { freq: 150, alt: ["bye"] }],
          ["hasta luego", "see you later", "phrase", { freq: 160 }],
          ["gracias", "thank you", "interjection", { freq: 60, alt: ["thanks"] }],
          ["qué tal", "how's it going", "phrase", { freq: 130, alt: ["how are you"] }],
          ["bien", "well, good", "adverb", { freq: 70, alt: ["good", "fine", "well"] }],
          ["y", "and", "function", { freq: 3 }],
        ],
        sentences: [
          ["Hola, ¿qué tal?", "Hi, how's it going?", { altEn: ["Hello, how are you?", "Hi, how are you?", "Hello, how's it going?"], note: "Spanish questions open with ¿ and close with ?." }],
          ["Bien, gracias.", "Good, thanks.", { altEn: ["Fine, thanks.", "Well, thank you.", "Good, thank you.", "Fine, thank you."] }],
          ["Buenos días.", "Good morning."],
          ["Buenas tardes.", "Good afternoon."],
          ["Buenas noches.", "Good night.", { altEn: ["Good evening."] }],
          ["Adiós, hasta luego.", "Goodbye, see you later.", { altEn: ["Bye, see you later."] }],
          ["Hola, buenos días.", "Hello, good morning.", { altEn: ["Hi, good morning."] }],
        ],
        concepts: ["questions"],
        speaking: [
          [1, "Hola, buenos días.", "Hello, good morning.", "Hola, buenos días.", "Hello, good morning.", ["hola", "buenos dias|buenos días"], { model: "Hola, buenos días." }],
          [3, "¿Qué tal?", "How's it going?", "Bien, gracias.", "Good, thanks.", ["bien|muy bien|mal|regular|mas o menos"]],
        ],
      },
      {
        title: "My name is…",
        titleEs: "Me llamo…",
        goal: "Say your name and ask someone theirs.",
        minutes: 6,
        vocab: [
          ["me llamo", "my name is", "phrase", { freq: 90, def: "lo que dices para decir tu nombre", alt: ["I am called", "I'm called"] }],
          ["¿cómo te llamas?", "what's your name?", "question", { freq: 110, keys: ["cómo te llamas"], alt: ["what is your name"] }],
          ["mucho gusto", "nice to meet you", "phrase", { freq: 200, alt: ["pleased to meet you"] }],
          ["¿y tú?", "and you?", "question", { freq: 100, keys: ["y tú"] }],
          ["yo", "I", "pronoun", { freq: 15 }],
          ["tú", "you (informal)", "pronoun", { freq: 20, keys: ["tu"], alt: ["you"] }],
          ["encantado", "delighted (to meet you)", "adjective", { freq: 400, alt: ["nice to meet you", "pleased to meet you"] }],
        ],
        sentences: [
          ["Hola, me llamo Ana.", "Hi, my name is Ana.", { altEn: ["Hello, my name is Ana.", "Hi, I'm Ana.", "Hello, I'm Ana.", "Hi, I am called Ana."], starter: "Hola, me…", note: "Me llamo literally means “I call myself.”" }],
          ["¿Cómo te llamas?", "What's your name?", { altEn: ["What is your name?"], note: "Te llamas = you call yourself. It's the informal way to ask." }],
          ["Me llamo Carlos, ¿y tú?", "My name is Carlos, and you?", { altEn: ["I'm Carlos, and you?", "My name is Carlos, and yours?"], starter: "Me llamo Carlos…" }],
          ["Mucho gusto.", "Nice to meet you.", { altEn: ["Pleased to meet you."] }],
          ["Encantado, yo me llamo Luis.", "Nice to meet you, my name is Luis.", { altEn: ["Pleased to meet you, my name is Luis.", "Delighted, I'm Luis."], note: "A woman would say encantada." }],
          ["Yo me llamo Sofía.", "My name is Sofía.", { altEn: ["I'm Sofía.", "My name is Sofia."], alt: ["Me llamo Sofía."] }],
        ],
        concepts: ["pronoun-drop"],
        speaking: [
          [1, "Hola, me llamo Carlos.", "Hi, my name is Carlos.", "Hola, me llamo Carlos.", "Hi, my name is Carlos.", ["hola", "me llamo"], { model: "Hola, me llamo Carlos." }],
          [2, "Me llamo _____.", "Complete it with your own name.", "Me llamo {name}.", "My name is {name}.", ["me llamo"], { starter: "Me llamo…" }],
          [3, "¿Cómo te llamas?", "What's your name?", "Me llamo {name}.", "My name is {name}.", ["me llamo|soy|mi nombre es"]],
        ],
      },
      {
        title: "Where are you from?",
        titleEs: "¿De dónde eres?",
        goal: "Say where you're from and ask others.",
        minutes: 6,
        vocab: [
          ["soy", "I am", "verb", { freq: 25, keys: ["soy"], lemma: "ser" }],
          ["de", "from, of", "function", { freq: 1 }],
          ["¿de dónde eres?", "where are you from?", "question", { freq: 240, keys: ["de dónde eres"] }],
          ["eres", "you are", "verb", { freq: 60, keys: ["eres"], lemma: "ser" }],
          ["Estados Unidos", "the United States", "noun", { freq: 600, keys: ["estados unidos"] }],
          ["México", "Mexico", "noun", { freq: 500, keys: ["méxico"] }],
          ["España", "Spain", "noun", { freq: 500, keys: ["españa"] }],
          ["también", "also, too", "adverb", { freq: 45, alt: ["too", "also"] }],
        ],
        sentences: [
          ["Soy de Estados Unidos.", "I'm from the United States.", { altEn: ["I am from the United States.", "I'm from the US.", "I am from the USA."], alt: ["Yo soy de Estados Unidos.", "Soy de los Estados Unidos."], starter: "Soy de…", c: ["ser-identity"] }],
          ["¿De dónde eres?", "Where are you from?", { c: ["ser-identity"] }],
          ["Soy de México, ¿y tú?", "I'm from Mexico, and you?", { altEn: ["I am from Mexico, and you?"], c: ["ser-identity"] }],
          ["Ella es de España.", "She's from Spain.", { altEn: ["She is from Spain."], c: ["ser-identity"] }],
          ["Yo también soy de México.", "I'm from Mexico too.", { altEn: ["I am also from Mexico.", "I'm also from Mexico.", "I am from Mexico too."], alt: ["También soy de México."], c: ["ser-identity"] }],
          ["Hola, me llamo Ana y soy de Chicago.", "Hi, my name is Ana and I'm from Chicago.", { altEn: ["Hello, my name is Ana and I am from Chicago.", "Hi, I'm Ana and I'm from Chicago."] }],
        ],
        concepts: ["ser-identity"],
        speaking: [
          [1, "Soy de Estados Unidos.", "I'm from the United States.", "Soy de Estados Unidos.", "I'm from the United States.", ["soy de"], { model: "Soy de Estados Unidos." }],
          [2, "Soy de _____.", "Say where you're from.", "Soy de Chicago.", "I'm from Chicago.", ["soy de"], { starter: "Soy de…" }],
          [3, "¿De dónde eres?", "Where are you from?", "Soy de Chicago.", "I'm from Chicago.", ["soy de|soy|de"]],
          [4, "Preséntate: tu nombre y de dónde eres.", "Introduce yourself: your name and where you're from.", "Hola, me llamo {name} y soy de Chicago.", "Hi, my name is {name} and I'm from Chicago.", ["me llamo|soy|mi nombre", "soy de|de"]],
        ],
      },
      {
        title: "How are you?",
        titleEs: "¿Cómo estás?",
        goal: "Ask how someone is and answer honestly.",
        minutes: 6,
        vocab: [
          ["¿cómo estás?", "how are you?", "question", { freq: 140, keys: ["cómo estás"] }],
          ["estoy", "I am (feeling / located)", "verb", { freq: 35, keys: ["estoy"], lemma: "estar", alt: ["I am", "I'm"] }],
          ["muy", "very", "adverb", { freq: 30 }],
          ["mal", "bad, badly", "adverb", { freq: 250, alt: ["bad", "not well"] }],
          ["más o menos", "so-so", "phrase", { freq: 300, alt: ["more or less", "okay"] }],
          ["sí", "yes", "interjection", { freq: 12, keys: ["sí"] }],
          ["no", "no, not", "function", { freq: 5 }],
          ["cansado", "tired", "adjective", { freq: 420, emoji: "😴", def: "cuando necesitas dormir" }],
        ],
        sentences: [
          ["¿Cómo estás?", "How are you?", { c: ["estar-states"] }],
          ["Estoy bien, gracias.", "I'm fine, thanks.", { altEn: ["I am fine, thank you.", "I'm good, thanks.", "I'm well, thank you.", "I am good, thanks."], alt: ["Bien, gracias."], starter: "Estoy…", c: ["estar-states"] }],
          ["Estoy muy bien.", "I'm very well.", { altEn: ["I am very well.", "I'm very good.", "I'm doing very well."], c: ["estar-states"] }],
          ["Más o menos.", "So-so.", { altEn: ["More or less.", "Okay."] }],
          ["No estoy mal.", "I'm not bad.", { altEn: ["I am not bad."], note: "No goes right before the verb.", c: ["estar-states"] }],
          ["Sí, estoy cansado.", "Yes, I'm tired.", { altEn: ["Yes, I am tired."], alt: ["Sí, estoy cansada."], c: ["estar-states"] }],
          ["¿Estás bien?", "Are you okay?", { altEn: ["Are you well?", "Are you all right?", "Are you alright?", "Are you ok?"], note: "A question can be the same words as a statement — only the tone and ¿? change." }],
        ],
        concepts: ["estar-states"],
        speaking: [
          [1, "Estoy muy bien, gracias.", "I'm very well, thanks.", "Estoy muy bien, gracias.", "I'm very well, thanks.", ["estoy", "bien"], { model: "Estoy muy bien, gracias." }],
          [3, "¿Cómo estás hoy?", "How are you today?", "Estoy un poco cansado, pero bien.", "I'm a little tired, but good.", ["estoy|bien|mal|mas o menos|cansado|cansada"]],
        ],
      },
      {
        title: "Basic questions",
        titleEs: "Preguntas básicas",
        goal: "Ask what, where and who — and say when you don't understand.",
        minutes: 7,
        vocab: [
          ["¿qué?", "what?", "question", { freq: 8, keys: ["qué"] }],
          ["¿dónde?", "where?", "question", { freq: 90, keys: ["dónde"] }],
          ["¿quién?", "who?", "question", { freq: 120, keys: ["quién"] }],
          ["hablar", "to speak", "verb", { freq: 95 }],
          ["español", "Spanish", "noun", { freq: 350, keys: ["español"] }],
          ["inglés", "English", "noun", { freq: 450, keys: ["inglés"] }],
          ["un poco", "a little", "phrase", { freq: 210 }],
          ["no entiendo", "I don't understand", "phrase", { freq: 330, def: "cuando algo no está claro para ti", alt: ["I do not understand"] }],
          ["el baño", "the bathroom", "noun", { g: "m", freq: 700, emoji: "🚻", alt: ["the restroom", "the toilet"] }],
          ["esto", "this", "pronoun", { freq: 55 }],
          ["está", "is (location / state)", "verb", { freq: 22, keys: ["está"], lemma: "estar", alt: ["is"] }],
          ["el", "the (masculine)", "function", { freq: 2 }],
          ["la", "the (feminine)", "function", { freq: 2 }],
        ],
        sentences: [
          ["¿Hablas español?", "Do you speak Spanish?", { note: "No “do” in Spanish questions — the verb does the work.", c: ["questions"] }],
          ["Sí, hablo un poco de español.", "Yes, I speak a little Spanish.", { altEn: ["Yes, I speak a bit of Spanish."], alt: ["Sí, hablo un poco español.", "Sí, hablo un poco."], starter: "Sí, hablo…" }],
          ["No entiendo.", "I don't understand.", { altEn: ["I do not understand."] }],
          ["¿Qué es esto?", "What is this?", { altEn: ["What's this?"] }],
          ["¿Dónde está el baño?", "Where is the bathroom?", { altEn: ["Where's the bathroom?", "Where is the restroom?", "Where's the restroom?", "Where is the toilet?"], starter: "¿Dónde…?", note: "Use está for where something is." }],
          ["¿Quién es?", "Who is it?", { altEn: ["Who is that?", "Who is he?", "Who is she?"] }],
          ["Hablo inglés y un poco de español.", "I speak English and a little Spanish.", { alt: ["Hablo inglés y un poco español."], altEn: ["I speak English and a bit of Spanish."] }],
        ],
        concepts: ["questions"],
        speaking: [
          [1, "No entiendo. ¿Puedes repetir?", "I don't understand. Can you repeat?", "No entiendo. ¿Puedes repetir?", "I don't understand. Can you repeat?", ["no entiendo"], { model: "No entiendo. ¿Puedes repetir?" }],
          [3, "¿Hablas español?", "Do you speak Spanish?", "Sí, hablo un poco de español.", "Yes, I speak a little Spanish.", ["hablo|si|un poco"]],
          [4, "Pregunta dónde está el baño.", "Ask where the bathroom is.", "¿Dónde está el baño?", "Where is the bathroom?", ["donde|dónde", "baño|bano"]],
        ],
      },
    ],
  },

  // ─── Unit 2 ────────────────────────────────────────────────────────────
  {
    title: "People and Numbers",
    description: "Talk about the people in your life, count, and say ages.",
    canDo: ["Describe people simply", "Talk about your family", "Count to one hundred", "Say how old someone is"],
    lessons: [
      {
        title: "People",
        titleEs: "Las personas",
        goal: "Point out and describe the people around you.",
        vocab: [
          ["el hombre", "the man", "noun", { g: "m", freq: 180, emoji: "👨" }],
          ["la mujer", "the woman", "noun", { g: "f", freq: 170, emoji: "👩", keys: ["mujer", "mujeres"] }],
          ["el chico", "the boy, the guy", "noun", { g: "m", freq: 400, alt: ["the boy", "the guy"] }],
          ["la chica", "the girl", "noun", { g: "f", freq: 400 }],
          ["el amigo", "the friend (male)", "noun", { g: "m", freq: 150, emoji: "🧑‍🤝‍🧑", alt: ["the friend"] }],
          ["la amiga", "the friend (female)", "noun", { g: "f", freq: 260, alt: ["the friend"] }],
          ["él", "he", "pronoun", { freq: 18, keys: ["él"] }],
          ["ella", "she", "pronoun", { freq: 24 }],
          ["es", "is (identity)", "verb", { freq: 4, keys: ["es"], lemma: "ser", alt: ["is"] }],
          ["simpático", "nice, friendly", "adjective", { freq: 900, def: "una persona agradable", alt: ["nice", "friendly"] }],
          ["mi", "my", "function", { freq: 14, keys: ["mi", "mis"] }],
          ["un", "a, an (masculine)", "function", { freq: 6 }],
          ["una", "a, an (feminine)", "function", { freq: 6 }],
        ],
        sentences: [
          ["Él es mi amigo.", "He's my friend.", { altEn: ["He is my friend."], c: ["ser-identity"] }],
          ["Ella es mi amiga.", "She's my friend.", { altEn: ["She is my friend."], note: "Amigo becomes amiga for a woman.", c: ["gender"] }],
          ["La chica es simpática.", "The girl is nice.", { altEn: ["The girl is friendly."], note: "Adjectives match the noun: la chica simpática.", c: ["gender"] }],
          ["Es un hombre muy simpático.", "He's a very nice man.", { altEn: ["He is a very nice man.", "He's a very friendly man.", "It's a very nice man."], c: ["gender"] }],
          ["¿Quién es ella?", "Who is she?", { altEn: ["Who's she?"] }],
          ["La mujer es de México.", "The woman is from Mexico.", { c: ["ser-identity"] }],
        ],
        concepts: ["gender"],
        speaking: [
          [1, "Ella es mi amiga.", "She's my friend.", "Ella es mi amiga.", "She's my friend.", ["ella", "amiga"], { model: "Ella es mi amiga." }],
          [4, "Habla de un amigo: ¿quién es y cómo es?", "Talk about a friend: who is he or she and what are they like?", "Mi amigo se llama Diego. Es muy simpático.", "My friend is called Diego. He's very nice.", ["amigo|amiga", "es"]],
        ],
      },
      {
        title: "Family",
        titleEs: "La familia",
        goal: "Talk about who is in your family.",
        vocab: [
          ["la familia", "the family", "noun", { g: "f", freq: 160, emoji: "👨‍👩‍👧" }],
          ["la madre", "the mother", "noun", { g: "f", freq: 210 }],
          ["el padre", "the father", "noun", { g: "m", freq: 210 }],
          ["los padres", "the parents", "noun", { g: "m", freq: 300, keys: ["padres"] }],
          ["el hermano", "the brother", "noun", { g: "m", freq: 260 }],
          ["la hermana", "the sister", "noun", { g: "f", freq: 280 }],
          ["el hijo", "the son", "noun", { g: "m", freq: 220 }],
          ["la hija", "the daughter", "noun", { g: "f", freq: 320 }],
          ["tener", "to have", "verb", { freq: 11 }],
          ["tu", "your (informal)", "function", { freq: 30, keys: ["tu", "tus"] }],
          ["se llama", "his / her name is", "phrase", { freq: 200, alt: ["is called", "her name is", "his name is"] }],
        ],
        sentences: [
          ["Mi madre se llama Rosa.", "My mother's name is Rosa.", { altEn: ["My mother is called Rosa.", "My mom's name is Rosa.", "My mom is called Rosa."] }],
          ["Tengo dos hermanos.", "I have two brothers.", { altEn: ["I have two siblings.", "I have two brothers and sisters."], note: "Hermanos can mean brothers or brothers and sisters.", c: ["tener-expressions"] }],
          ["¿Tienes hermanos?", "Do you have siblings?", { altEn: ["Do you have any brothers or sisters?", "Do you have brothers?", "Do you have any siblings?"] }],
          ["Mi hermana es muy simpática.", "My sister is very nice.", { c: ["gender"] }],
          ["Mis padres son de Colombia.", "My parents are from Colombia.", { note: "Mi becomes mis before a plural noun.", c: ["possessives", "ser-identity"] }],
          ["Tengo un hijo y una hija.", "I have a son and a daughter.", { c: ["gender"] }],
          ["¿Cómo se llama tu padre?", "What's your father's name?", { altEn: ["What is your father's name?", "What is your dad's name?", "What's your dad called?"], c: ["possessives"] }],
        ],
        concepts: ["possessives"],
        speaking: [
          [1, "Mi madre se llama Rosa.", "My mother's name is Rosa.", "Mi madre se llama Rosa.", "My mother's name is Rosa.", ["madre", "se llama"], { model: "Mi madre se llama Rosa." }],
          [3, "¿Tienes hermanos?", "Do you have siblings?", "Sí, tengo una hermana.", "Yes, I have a sister.", ["tengo|no tengo|si|no"]],
          [4, "Describe a tu familia.", "Describe your family.", "Tengo una familia pequeña: mi madre, mi padre y un hermano.", "I have a small family: my mom, my dad and a brother.", ["tengo|mi familia|mi", "madre|padre|hermano|hermana|hijo|hija|padres"]],
        ],
      },
      {
        title: "Numbers 0–20",
        titleEs: "Los números",
        goal: "Count and use small numbers in real sentences.",
        vocab: [
          ["cero", "zero", "number", { freq: 700 }],
          ["uno", "one", "number", { freq: 50, keys: ["uno"] }],
          ["dos", "two", "number", { freq: 40, emoji: "2️⃣" }],
          ["tres", "three", "number", { freq: 60 }],
          ["cuatro", "four", "number", { freq: 90 }],
          ["cinco", "five", "number", { freq: 90, emoji: "🖐️" }],
          ["seis", "six", "number", { freq: 120 }],
          ["siete", "seven", "number", { freq: 150 }],
          ["ocho", "eight", "number", { freq: 150 }],
          ["nueve", "nine", "number", { freq: 170 }],
          ["diez", "ten", "number", { freq: 100 }],
          ["quince", "fifteen", "number", { freq: 300 }],
          ["veinte", "twenty", "number", { freq: 200 }],
          ["hay", "there is, there are", "verb", { freq: 28, keys: ["hay"], lemma: "haber", alt: ["there is", "there are"] }],
          ["la persona", "the person", "noun", { g: "f", freq: 120 }],
          ["el número", "the number", "noun", { g: "m", freq: 400 }],
        ],
        sentences: [
          ["Hay diez personas.", "There are ten people.", { c: ["hay-esta"] }],
          ["Tengo tres hermanas.", "I have three sisters."],
          ["Mi número es el cinco.", "My number is five.", { altEn: ["My number is the five."] }],
          ["Hay veinte chicos y quince chicas.", "There are twenty boys and fifteen girls.", { altEn: ["There are twenty guys and fifteen girls."] }],
          ["¿Hay un baño?", "Is there a bathroom?", { altEn: ["Is there a restroom?"], c: ["hay-esta"] }],
          ["Uno, dos, tres, cuatro, cinco.", "One, two, three, four, five."],
        ],
        concepts: ["hay-esta"],
        speaking: [
          [1, "Uno, dos, tres, cuatro, cinco, seis, siete, ocho, nueve, diez.", "Count from one to ten.", "Uno, dos, tres, cuatro, cinco, seis, siete, ocho, nueve, diez.", "One to ten.", ["uno", "cinco", "diez"], { model: "Uno, dos, tres, cuatro, cinco, seis, siete, ocho, nueve, diez." }],
          [3, "¿Cuántas personas hay en tu familia?", "How many people are in your family?", "Hay cuatro personas en mi familia.", "There are four people in my family.", ["hay|somos|son", "dos|tres|cuatro|cinco|seis|siete|ocho"]],
        ],
      },
      {
        title: "How old are you?",
        titleEs: "¿Cuántos años tienes?",
        goal: "Ask and give ages using tener.",
        vocab: [
          ["el año", "the year", "noun", { g: "m", freq: 45 }],
          ["¿cuántos?", "how many?", "question", { freq: 350, keys: ["cuántos", "cuántas"] }],
          ["treinta", "thirty", "number", { freq: 350 }],
          ["cuarenta", "forty", "number", { freq: 450 }],
          ["cincuenta", "fifty", "number", { freq: 450 }],
          ["cien", "one hundred", "number", { freq: 300, keys: ["cien", "ciento"] }],
          ["el cumpleaños", "the birthday", "noun", { g: "m", freq: 900, emoji: "🎂", keys: ["cumpleaños"] }],
        ],
        sentences: [
          ["¿Cuántos años tienes?", "How old are you?", { note: "Spanish says “how many years do you have?” — age uses tener.", c: ["tener-expressions"] }],
          ["Tengo veinte años.", "I'm twenty years old.", { altEn: ["I am twenty years old.", "I'm twenty.", "I am twenty."], alt: ["Yo tengo veinte años."], starter: "Tengo…", c: ["tener-expressions"] }],
          ["Mi padre tiene cincuenta años.", "My father is fifty years old.", { altEn: ["My father is fifty.", "My dad is fifty years old.", "My dad is fifty."], c: ["tener-expressions"] }],
          ["Mi hermana tiene quince años.", "My sister is fifteen years old.", { altEn: ["My sister is fifteen."], c: ["tener-expressions"] }],
          ["¿Cuántos años tiene tu madre?", "How old is your mother?", { altEn: ["How old is your mom?"], c: ["tener-expressions"] }],
          ["Hoy es mi cumpleaños.", "Today is my birthday."],
        ],
        concepts: ["tener-expressions"],
        speaking: [
          [2, "Tengo _____ años.", "Say your age.", "Tengo veinte años.", "I'm twenty years old.", ["tengo", "anos|años"], { starter: "Tengo… años." }],
          [3, "¿Cuántos años tienes?", "How old are you?", "Tengo veinte años.", "I'm twenty.", ["tengo"]],
          [4, "¿Cuántos años tiene alguien de tu familia?", "How old is someone in your family?", "Mi madre tiene cincuenta años.", "My mother is fifty.", ["tiene", "anos|años"]],
        ],
      },
    ],
  },

  // ─── Unit 3 ────────────────────────────────────────────────────────────
  {
    title: "Food and Drink",
    description: "Say what you want, what you like, and order at a restaurant.",
    canDo: ["Say you're hungry or thirsty", "Talk about food you like", "Order food and drinks", "Ask for the bill"],
    lessons: [
      {
        title: "I'm hungry",
        titleEs: "Tengo hambre",
        goal: "Say you're hungry or thirsty and what you want.",
        vocab: [
          ["tener hambre", "to be hungry", "phrase", { freq: 500, keys: ["hambre"], emoji: "🍽️", def: "cuando quieres comer" }],
          ["tener sed", "to be thirsty", "phrase", { freq: 800, keys: ["sed"], emoji: "🥤", def: "cuando quieres beber" }],
          ["comer", "to eat", "verb", { freq: 120, emoji: "🍴" }],
          ["beber", "to drink", "verb", { freq: 300 }],
          ["querer", "to want", "verb", { freq: 19 }],
          ["el agua", "the water", "noun", { g: "f", freq: 250, emoji: "💧", def: "lo que bebes cuando tienes sed" }],
          ["mucho", "a lot, much", "adjective", { freq: 40, alt: ["a lot", "much", "very"] }],
        ],
        sentences: [
          ["Tengo hambre.", "I'm hungry.", { altEn: ["I am hungry."], note: "Spanish says “I have hunger.” Estoy hambre is not correct.", starter: "Tengo…", c: ["tener-expressions"] }],
          ["Tengo mucha hambre.", "I'm very hungry.", { altEn: ["I am very hungry.", "I'm really hungry."], note: "Hambre is feminine, so mucho becomes mucha.", c: ["tener-expressions", "gender"] }],
          ["¿Tienes hambre?", "Are you hungry?", { c: ["tener-expressions"] }],
          ["No tengo hambre.", "I'm not hungry.", { altEn: ["I am not hungry."], c: ["tener-expressions"] }],
          ["Tengo sed.", "I'm thirsty.", { altEn: ["I am thirsty."], c: ["tener-expressions"] }],
          ["Quiero beber agua.", "I want to drink water.", { altEn: ["I want to drink some water."], alt: ["Quiero tomar agua."], c: ["stem-changing"] }],
          ["¿Quieres comer?", "Do you want to eat?", { altEn: ["Would you like to eat?", "Do you want to eat something?"], c: ["stem-changing"] }],
          ["Quiero comer.", "I want to eat.", { alt: ["Yo quiero comer.", "Tengo ganas de comer."], altEn: ["I'd like to eat."], c: ["stem-changing"] }],
        ],
        concepts: ["tener-expressions", "stem-changing"],
        speaking: [
          [1, "Tengo mucha hambre.", "I'm very hungry.", "Tengo mucha hambre.", "I'm very hungry.", ["tengo", "hambre"], { model: "Tengo mucha hambre." }],
          [4, "Say that you are very hungry.", "", "Tengo mucha hambre.", "I'm very hungry.", ["tengo", "hambre"]],
          [3, "¿Tienes sed?", "Are you thirsty?", "Sí, tengo sed. Quiero agua.", "Yes, I'm thirsty. I want water.", ["tengo|no tengo|si|no"]],
        ],
      },
      {
        title: "Food I like",
        titleEs: "Me gusta la comida",
        goal: "Say what you like and don't like to eat.",
        vocab: [
          ["me gusta", "I like", "phrase", { freq: 150, keys: ["me gusta", "me gustan"], def: "cuando algo te parece bueno" }],
          ["¿te gusta?", "do you like?", "question", { freq: 300, keys: ["te gusta", "te gustan"] }],
          ["el pan", "the bread", "noun", { g: "m", freq: 600, emoji: "🍞" }],
          ["el arroz", "the rice", "noun", { g: "m", freq: 900, emoji: "🍚" }],
          ["el pollo", "the chicken", "noun", { g: "m", freq: 900, emoji: "🍗" }],
          ["la fruta", "the fruit", "noun", { g: "f", freq: 900, emoji: "🍎" }],
          ["la manzana", "the apple", "noun", { g: "f", freq: 1000, emoji: "🍏" }],
          ["el queso", "the cheese", "noun", { g: "m", freq: 1000, emoji: "🧀" }],
          ["la carne", "the meat", "noun", { g: "f", freq: 800, emoji: "🥩" }],
          ["la comida", "the food, the meal", "noun", { g: "f", freq: 250, alt: ["food", "the meal"] }],
          ["con", "with", "function", { freq: 9 }],
          ["los", "the (masc. plural)", "function", { freq: 4 }],
          ["las", "the (fem. plural)", "function", { freq: 4 }],
        ],
        sentences: [
          ["Me gusta el pollo.", "I like chicken.", { altEn: ["I like the chicken."], note: "Literally “chicken pleases me.” The thing you like is the subject.", starter: "Me gusta…", c: ["gustar"] }],
          ["No me gusta el queso.", "I don't like cheese.", { altEn: ["I do not like cheese.", "I don't like the cheese."], c: ["gustar"] }],
          ["Me gustan las manzanas.", "I like apples.", { note: "Plural thing → gustan.", c: ["gustar"] }],
          ["¿Te gusta la fruta?", "Do you like fruit?", { c: ["gustar"] }],
          ["Como arroz con pollo.", "I eat rice with chicken.", { altEn: ["I'm eating rice with chicken.", "I eat chicken with rice."] }],
          ["Me gusta mucho el pan.", "I really like bread.", { altEn: ["I like bread a lot.", "I like the bread a lot."], c: ["gustar"] }],
          ["No me gusta la carne.", "I don't like meat.", { altEn: ["I do not like meat."], c: ["gustar"] }],
        ],
        concepts: ["gustar"],
        speaking: [
          [1, "Me gusta mucho el pollo con arroz.", "I really like chicken with rice.", "Me gusta mucho el pollo con arroz.", "I really like chicken with rice.", ["me gusta", "pollo"], { model: "Me gusta mucho el pollo con arroz." }],
          [3, "¿Qué comida te gusta?", "What food do you like?", "Me gusta la pizza y me gustan las manzanas.", "I like pizza and I like apples.", ["me gusta|me gustan"]],
          [5, "Describe esta imagen.", "Describe this picture.", "Hay pollo, arroz y fruta.", "There's chicken, rice and fruit.", ["hay|es|me gusta", "pollo|arroz|fruta|manzana|pan|queso"], { scene: "🍗🍚🍎🍞" }],
        ],
      },
      {
        title: "Drinks",
        titleEs: "Las bebidas",
        goal: "Order drinks exactly how you like them.",
        vocab: [
          ["el café", "the coffee", "noun", { g: "m", freq: 500, emoji: "☕" }],
          ["el té", "the tea", "noun", { g: "m", freq: 900, emoji: "🍵", keys: ["té"] }],
          ["la leche", "the milk", "noun", { g: "f", freq: 800, emoji: "🥛" }],
          ["el jugo", "the juice", "noun", { g: "m", freq: 1200, emoji: "🧃", region: "Latin America (Spain: el zumo)", keys: ["jugo", "jugos", "zumo"] }],
          ["la naranja", "the orange", "noun", { g: "f", freq: 1200, emoji: "🍊" }],
          ["sin", "without", "function", { freq: 80 }],
          ["el azúcar", "the sugar", "noun", { g: "m", freq: 1500, keys: ["azúcar"] }],
          ["frío", "cold", "adjective", { freq: 600, emoji: "🧊" }],
          ["caliente", "hot", "adjective", { freq: 900, emoji: "🔥" }],
          ["por favor", "please", "phrase", { freq: 70 }],
        ],
        sentences: [
          ["Quiero un café con leche.", "I want a coffee with milk.", { altEn: ["I'd like a coffee with milk.", "I want a latte."], alt: ["Quisiera un café con leche."] }],
          ["Un té sin azúcar, por favor.", "A tea without sugar, please.", { altEn: ["A tea with no sugar, please."] }],
          ["¿Quieres un jugo de naranja?", "Do you want an orange juice?", { altEn: ["Would you like an orange juice?", "Do you want orange juice?"], alt: ["¿Quieres un zumo de naranja?"] }],
          ["El café está caliente.", "The coffee is hot.", { note: "Temperature right now is a state → estar.", c: ["estar-states"] }],
          ["Quiero agua fría.", "I want cold water.", { altEn: ["I'd like cold water."], note: "Agua uses el, but it's feminine: agua fría.", c: ["gender"] }],
          ["Un café, por favor.", "A coffee, please.", { altEn: ["One coffee, please."] }],
        ],
        speaking: [
          [1, "Un café con leche, por favor.", "A coffee with milk, please.", "Un café con leche, por favor.", "A coffee with milk, please.", ["cafe|café", "por favor"], { model: "Un café con leche, por favor." }],
          [4, "Order your favorite drink politely.", "", "Un té sin azúcar, por favor.", "A tea without sugar, please.", ["cafe|te|té|agua|jugo|leche|zumo", "por favor"]],
        ],
      },
      {
        title: "At the restaurant",
        titleEs: "En el restaurante",
        goal: "Get a table, order a meal and pay.",
        kind: "scenario",
        scenario: "restaurant",
        minutes: 8,
        vocab: [
          ["la mesa", "the table", "noun", { g: "f", freq: 600, emoji: "🪑" }],
          ["el menú", "the menu", "noun", { g: "m", freq: 1500, keys: ["menú", "carta"] }],
          ["la cuenta", "the bill, the check", "noun", { g: "f", freq: 500, emoji: "🧾", alt: ["the check", "the bill"] }],
          ["el mesero", "the waiter", "noun", { g: "m", freq: 2000, region: "Latin America (Spain: el camarero)", keys: ["mesero", "meseros", "mesera", "camarero", "camarera"] }],
          ["quisiera", "I would like", "phrase", { freq: 700, def: "forma educada de decir quiero", alt: ["I'd like"] }],
          ["para mí", "for me", "phrase", { freq: 400, keys: ["para mí", "para mi"] }],
          ["algo más", "anything else, something else", "phrase", { freq: 500, alt: ["anything else", "something else"] }],
          ["nada más", "nothing else", "phrase", { freq: 800 }],
          ["¿me trae…?", "could you bring me…?", "question", { freq: 1500, keys: ["me trae"], alt: ["can you bring me"] }],
          ["para", "for", "function", { freq: 13 }],
        ],
        sentences: [
          ["Una mesa para dos, por favor.", "A table for two, please."],
          ["¿Me trae el menú, por favor?", "Could you bring me the menu, please?", { altEn: ["Can you bring me the menu, please?", "Can I have the menu, please?"], alt: ["¿Me trae la carta, por favor?"] }],
          ["Para mí, el pollo con arroz.", "For me, the chicken with rice.", { altEn: ["I'll have the chicken with rice."] }],
          ["Quisiera un agua, por favor.", "I would like a water, please.", { altEn: ["I'd like a water, please.", "I would like some water, please."], note: "Quisiera is softer and more polite than quiero." }],
          ["La cuenta, por favor.", "The check, please.", { altEn: ["The bill, please."] }],
          ["¿Algo más?", "Anything else?"],
          ["Nada más, gracias.", "Nothing else, thanks.", { altEn: ["Nothing else, thank you.", "That's all, thanks."] }],
        ],
        speaking: [
          [1, "La cuenta, por favor.", "The check, please.", "La cuenta, por favor.", "The check, please.", ["cuenta"], { model: "La cuenta, por favor." }],
          [6, "Buenas tardes. ¿Qué desea?", "Good afternoon. What would you like?", "Quisiera el pollo con arroz y un agua, por favor.", "I'd like the chicken with rice and a water, please.", ["quiero|quisiera|para mi|me trae|me da", "pollo|arroz|agua|cafe|carne|pan|queso|jugo|té|te"]],
        ],
      },
    ],
  },

  // ─── Unit 4 ────────────────────────────────────────────────────────────
  {
    title: "Everyday Life",
    description: "Describe your routine, days and times — and feel the difference between ser and estar.",
    canDo: ["Talk about your routine", "Tell the time", "Talk about the days of the week", "Describe how you feel today"],
    lessons: [
      {
        title: "Everyday verbs",
        titleEs: "Verbos de todos los días",
        goal: "Say what you do: work, study, live, read.",
        vocab: [
          ["trabajar", "to work", "verb", { freq: 110 }],
          ["estudiar", "to study", "verb", { freq: 300 }],
          ["vivir", "to live", "verb", { freq: 100, emoji: "🏡" }],
          ["leer", "to read", "verb", { freq: 350, emoji: "📖" }],
          ["escribir", "to write", "verb", { freq: 300, emoji: "✍️" }],
          ["la casa", "the house, home", "noun", { g: "f", freq: 65, emoji: "🏠", def: "el lugar donde vives", alt: ["the house", "home"] }],
          ["el libro", "the book", "noun", { g: "m", freq: 300, emoji: "📚" }],
          ["la universidad", "the university", "noun", { g: "f", freq: 700 }],
          ["pequeño", "small", "adjective", { freq: 250 }],
          ["en", "in, at, on", "function", { freq: 3 }],
          ["todos los días", "every day", "phrase", { freq: 400 }],
        ],
        sentences: [
          ["Trabajo en una oficina.", "I work in an office.", { alt: ["Yo trabajo en una oficina."], c: ["present-regular"] }],
          ["Estudio español todos los días.", "I study Spanish every day.", { c: ["present-regular"] }],
          ["¿Dónde vives?", "Where do you live?", { c: ["present-regular"] }],
          ["Vivo en una casa pequeña.", "I live in a small house.", { note: "Most adjectives go after the noun.", starter: "Vivo en…", c: ["present-regular", "gender"] }],
          ["Mi hermano estudia en la universidad.", "My brother studies at the university.", { altEn: ["My brother studies at university.", "My brother is studying at the university."], c: ["present-regular"] }],
          ["Leo un libro.", "I'm reading a book.", { altEn: ["I read a book.", "I am reading a book."], c: ["present-regular"] }],
          ["Ella escribe en español.", "She writes in Spanish.", { altEn: ["She's writing in Spanish."], c: ["present-regular"] }],
        ],
        concepts: ["present-regular"],
        speaking: [
          [1, "Vivo en una casa pequeña.", "I live in a small house.", "Vivo en una casa pequeña.", "I live in a small house.", ["vivo", "casa"], { model: "Vivo en una casa pequeña." }],
          [3, "¿Dónde vives?", "Where do you live?", "Vivo en Chicago, en un apartamento.", "I live in Chicago, in an apartment.", ["vivo"]],
          [3, "¿Trabajas o estudias?", "Do you work or study?", "Trabajo en una oficina y estudio español.", "I work in an office and I study Spanish.", ["trabajo|estudio"]],
        ],
      },
      {
        title: "Days of the week",
        titleEs: "Los días",
        goal: "Talk about what happens on which day.",
        vocab: [
          ["lunes", "Monday", "noun", { g: "m", freq: 700 }],
          ["martes", "Tuesday", "noun", { g: "m", freq: 800 }],
          ["miércoles", "Wednesday", "noun", { g: "m", freq: 900 }],
          ["jueves", "Thursday", "noun", { g: "m", freq: 900 }],
          ["viernes", "Friday", "noun", { g: "m", freq: 700 }],
          ["sábado", "Saturday", "noun", { g: "m", freq: 700 }],
          ["domingo", "Sunday", "noun", { g: "m", freq: 700 }],
          ["hoy", "today", "adverb", { freq: 80, def: "este día" }],
          ["mañana", "tomorrow", "adverb", { freq: 110, def: "el día después de hoy", keys: ["mañana"] }],
          ["el fin de semana", "the weekend", "noun", { g: "m", freq: 500, keys: ["fin de semana"] }],
          ["hacer", "to do, to make", "verb", { freq: 26 }],
        ],
        sentences: [
          ["Hoy es lunes.", "Today is Monday.", { note: "Days aren't capitalized in Spanish." }],
          ["Mañana es martes.", "Tomorrow is Tuesday."],
          ["Trabajo de lunes a viernes.", "I work Monday to Friday.", { altEn: ["I work from Monday to Friday.", "I work Monday through Friday."] }],
          ["El sábado no trabajo.", "On Saturday I don't work.", { altEn: ["I don't work on Saturday.", "I don't work on Saturdays."], note: "“On Saturday” is just el sábado — no word for “on.”" }],
          ["¿Qué haces el fin de semana?", "What do you do on the weekend?", { altEn: ["What are you doing on the weekend?", "What do you do at the weekend?", "What are you doing this weekend?"] }],
          ["Los domingos como con mi familia.", "On Sundays I eat with my family.", { altEn: ["I eat with my family on Sundays."] }],
        ],
        speaking: [
          [3, "¿Qué día es hoy?", "What day is today?", "Hoy es miércoles.", "Today is Wednesday.", ["hoy es|es", "lunes|martes|miercoles|miércoles|jueves|viernes|sabado|sábado|domingo"]],
          [4, "¿Qué haces los sábados?", "What do you do on Saturdays?", "Los sábados no trabajo. Como con mis amigos.", "On Saturdays I don't work. I eat with my friends.", ["sabado|sábado|sabados|sábados|no|como|leo|estudio|trabajo"]],
        ],
      },
      {
        title: "What time is it?",
        titleEs: "¿Qué hora es?",
        goal: "Tell the time and say when things happen.",
        vocab: [
          ["la hora", "the hour, the time", "noun", { g: "f", freq: 180, emoji: "🕒" }],
          ["¿qué hora es?", "what time is it?", "question", { freq: 600, keys: ["qué hora es"] }],
          ["es la una", "it's one o'clock", "phrase", { freq: 900 }],
          ["son las", "it's … (o'clock)", "phrase", { freq: 700, keys: ["son las"] }],
          ["y media", "half past", "phrase", { freq: 700, alt: ["thirty"] }],
          ["y cuarto", "quarter past", "phrase", { freq: 900 }],
          ["de la mañana", "in the morning (a.m.)", "phrase", { freq: 500 }],
          ["de la tarde", "in the afternoon (p.m.)", "phrase", { freq: 500 }],
          ["de la noche", "at night (p.m.)", "phrase", { freq: 600 }],
          ["a", "to, at", "function", { freq: 3 }],
        ],
        sentences: [
          ["¿Qué hora es?", "What time is it?", { c: ["telling-time"] }],
          ["Es la una.", "It's one o'clock.", { altEn: ["It is one o'clock.", "It's one."], note: "Una is singular, so it's es la una — every other hour uses son las.", c: ["telling-time"] }],
          ["Son las tres y media.", "It's three thirty.", { altEn: ["It is half past three.", "It's half past three.", "It is three thirty."], c: ["telling-time"] }],
          ["Son las ocho de la mañana.", "It's eight in the morning.", { altEn: ["It is eight in the morning.", "It's 8 a.m."], c: ["telling-time"] }],
          ["Como a las dos de la tarde.", "I eat at two in the afternoon.", { altEn: ["I have lunch at two in the afternoon.", "I eat at 2 p.m."], note: "“At” a time is a las.", c: ["telling-time"] }],
          ["¿A qué hora trabajas?", "What time do you work?", { altEn: ["At what time do you work?", "When do you work?"], c: ["telling-time"] }],
        ],
        concepts: ["telling-time"],
        speaking: [
          [1, "Son las tres y media.", "It's three thirty.", "Son las tres y media.", "It's three thirty.", ["son las", "tres", "media"], { model: "Son las tres y media." }],
          [3, "¿A qué hora comes?", "What time do you eat?", "Como a la una de la tarde.", "I eat at one in the afternoon.", ["a las|a la"]],
        ],
      },
      {
        title: "My routine",
        titleEs: "Mi rutina",
        goal: "Walk someone through your day.",
        minutes: 7,
        vocab: [
          ["levantarse", "to get up", "verb", { freq: 900, emoji: "⏰" }],
          ["ducharse", "to shower", "verb", { freq: 2000, emoji: "🚿" }],
          ["desayunar", "to have breakfast", "verb", { freq: 1500, emoji: "🥣" }],
          ["almorzar", "to have lunch", "verb", { freq: 1800 }],
          ["cenar", "to have dinner", "verb", { freq: 1500 }],
          ["acostarse", "to go to bed", "verb", { freq: 1600, emoji: "🛏️" }],
          ["temprano", "early", "adverb", { freq: 900 }],
          ["tarde", "late", "adverb", { freq: 300, keys: ["tarde"] }],
          ["primero", "first", "adverb", { freq: 350 }],
          ["después", "afterwards, then", "adverb", { freq: 200, alt: ["then", "after", "afterwards"] }],
          ["me", "myself (reflexive)", "function", { freq: 10 }],
          ["te", "yourself, you", "function", { freq: 25 }],
        ],
        sentences: [
          ["Me levanto a las siete.", "I get up at seven.", { altEn: ["I get up at seven o'clock.", "I wake up at seven."], note: "Levantarse: you “get yourself up,” so me goes before the verb.", c: ["reflexive"] }],
          ["Primero me ducho y después desayuno.", "First I shower and then I have breakfast.", { altEn: ["First I take a shower and then I eat breakfast.", "First I shower and afterwards I have breakfast."], c: ["reflexive"] }],
          ["Almuerzo a la una.", "I have lunch at one.", { altEn: ["I eat lunch at one."], note: "Almorzar changes o → ue: almuerzo.", c: ["stem-changing"] }],
          ["Ceno con mi familia.", "I have dinner with my family.", { altEn: ["I eat dinner with my family."] }],
          ["Me acuesto tarde.", "I go to bed late.", { c: ["reflexive", "stem-changing"] }],
          ["¿A qué hora te levantas?", "What time do you get up?", { altEn: ["When do you get up?"], c: ["reflexive"] }],
        ],
        concepts: ["reflexive"],
        speaking: [
          [1, "Me levanto a las siete y desayuno.", "I get up at seven and have breakfast.", "Me levanto a las siete y desayuno.", "I get up at seven and have breakfast.", ["me levanto", "desayuno"], { model: "Me levanto a las siete y desayuno." }],
          [3, "¿A qué hora te levantas?", "What time do you get up?", "Me levanto a las siete.", "I get up at seven.", ["me levanto|levanto"]],
          [4, "Describe tu mañana.", "Describe your morning.", "Me levanto a las siete, me ducho y después desayuno.", "I get up at seven, shower and then have breakfast.", ["me levanto|me ducho|desayuno", "primero|despues|después|y"]],
        ],
      },
      {
        title: "Ser and estar",
        titleEs: "Ser y estar",
        goal: "Choose the right “to be” for who you are vs. how you are.",
        minutes: 8,
        vocab: [
          ["contento", "happy, pleased", "adjective", { freq: 1100, emoji: "😊", def: "cuando algo te pone de buen humor" }],
          ["ocupado", "busy", "adjective", { freq: 1300 }],
          ["feliz", "happy", "adjective", { freq: 700, def: "sentirse bien porque algo bueno pasó", keys: ["feliz", "felices"] }],
          ["triste", "sad", "adjective", { freq: 900, emoji: "😢", def: "lo contrario de feliz" }],
          ["alto", "tall", "adjective", { freq: 500 }],
          ["joven", "young", "adjective", { freq: 400, keys: ["joven", "jóvenes"] }],
          ["aquí", "here", "adverb", { freq: 90 }],
          ["estamos", "we are (state / location)", "verb", { freq: 200, keys: ["estamos"], lemma: "estar" }],
          ["estar", "to be (state, location)", "verb", { freq: 12 }],
        ],
        sentences: [
          ["Estoy cansado.", "I'm tired.", { alt: ["Estoy cansada."], altEn: ["I am tired."], note: "Tired is a state right now → estar.", c: ["ser-estar"] }],
          ["Hoy estoy muy ocupada.", "Today I'm very busy.", { alt: ["Hoy estoy muy ocupado."], altEn: ["I'm very busy today.", "I am very busy today."], c: ["ser-estar"] }],
          ["Soy alto.", "I'm tall.", { alt: ["Soy alta."], altEn: ["I am tall."], note: "Being tall is part of who you are → ser.", c: ["ser-estar"] }],
          ["Mi madre es muy joven.", "My mother is very young.", { altEn: ["My mom is very young."], c: ["ser-estar"] }],
          ["Estamos en casa.", "We're at home.", { altEn: ["We are at home.", "We're home.", "We are home."], note: "Location → estar.", c: ["ser-estar"] }],
          ["¿Estás contento?", "Are you happy?", { alt: ["¿Estás contenta?"], altEn: ["Are you pleased?"], c: ["ser-estar"] }],
          ["Ella está triste hoy.", "She's sad today.", { altEn: ["She is sad today."], c: ["ser-estar"] }],
          ["Soy de Chicago, pero estoy en Madrid.", "I'm from Chicago, but I'm in Madrid.", { altEn: ["I am from Chicago, but I am in Madrid."], note: "Origin → ser. Where you are now → estar.", c: ["ser-estar"] }],
        ],
        concepts: ["ser-estar"],
        speaking: [
          [1, "Soy de Chicago, pero estoy en Madrid.", "I'm from Chicago, but I'm in Madrid.", "Soy de Chicago, pero estoy en Madrid.", "I'm from Chicago, but I'm in Madrid.", ["soy de", "estoy en"], { model: "Soy de Chicago, pero estoy en Madrid." }],
          [3, "¿Cómo estás hoy?", "How are you today?", "Hoy estoy un poco cansado, pero contento.", "Today I'm a bit tired, but happy.", ["estoy"]],
          [4, "Describe a una persona: ¿cómo es y cómo está hoy?", "Describe someone: what are they like and how are they today?", "Mi hermana es alta y simpática. Hoy está muy ocupada.", "My sister is tall and nice. Today she's very busy.", ["es", "esta|está"]],
        ],
      },
    ],
  },

  // ─── Unit 5 ────────────────────────────────────────────────────────────
  {
    title: "Getting Around",
    description: "Find places, follow directions and talk about how you travel.",
    canDo: ["Ask where places are", "Follow simple directions", "Talk about transportation", "Say what you're going to do"],
    lessons: [
      {
        title: "Places in town",
        titleEs: "Los lugares",
        goal: "Ask whether a place is nearby and where it is.",
        vocab: [
          ["el banco", "the bank", "noun", { g: "m", freq: 700, emoji: "🏦" }],
          ["el supermercado", "the supermarket", "noun", { g: "m", freq: 1500, emoji: "🛒" }],
          ["la farmacia", "the pharmacy", "noun", { g: "f", freq: 1600, emoji: "💊" }],
          ["el hotel", "the hotel", "noun", { g: "m", freq: 900, emoji: "🏨" }],
          ["el parque", "the park", "noun", { g: "m", freq: 900, emoji: "🌳" }],
          ["el restaurante", "the restaurant", "noun", { g: "m", freq: 900 }],
          ["cerca", "near, nearby", "adverb", { freq: 350 }],
          ["lejos", "far", "adverb", { freq: 600 }],
          ["el centro", "the center, downtown", "noun", { g: "m", freq: 400, alt: ["downtown", "the center"] }],
          ["bonito", "pretty, nice", "adjective", { freq: 800, alt: ["pretty", "beautiful", "nice"] }],
        ],
        sentences: [
          ["¿Hay un banco cerca?", "Is there a bank nearby?", { altEn: ["Is there a bank near here?", "Is there a bank close by?"], note: "Hay asks whether something exists.", c: ["hay-esta"] }],
          ["El supermercado está cerca.", "The supermarket is close.", { altEn: ["The supermarket is nearby.", "The supermarket is near."], note: "Está tells you where a specific place is.", c: ["hay-esta"] }],
          ["La farmacia está lejos.", "The pharmacy is far.", { altEn: ["The pharmacy is far away."], c: ["hay-esta"] }],
          ["Hay un parque muy bonito.", "There's a very pretty park.", { altEn: ["There is a very nice park.", "There's a very nice park.", "There is a very beautiful park."], c: ["hay-esta"] }],
          ["El hotel está en el centro.", "The hotel is downtown.", { altEn: ["The hotel is in the center.", "The hotel is in the city center."], c: ["hay-esta"] }],
          ["¿Dónde está el restaurante?", "Where is the restaurant?", { altEn: ["Where's the restaurant?"], c: ["hay-esta"] }],
        ],
        concepts: ["hay-esta"],
        speaking: [
          [1, "¿Hay una farmacia cerca?", "Is there a pharmacy nearby?", "¿Hay una farmacia cerca?", "Is there a pharmacy nearby?", ["hay", "farmacia"], { model: "¿Hay una farmacia cerca?" }],
          [4, "Ask if there's a supermarket nearby.", "", "¿Hay un supermercado cerca?", "Is there a supermarket nearby?", ["hay", "supermercado"]],
          [5, "Describe esta imagen.", "Describe this picture.", "Hay un parque, un banco y un hotel.", "There's a park, a bank and a hotel.", ["hay", "parque|banco|hotel|restaurante"], { scene: "🌳🏦🏨" }],
        ],
      },
      {
        title: "Directions",
        titleEs: "Las direcciones",
        goal: "Ask how to get somewhere and understand the answer.",
        minutes: 7,
        vocab: [
          ["a la derecha", "to the right", "phrase", { freq: 800, emoji: "➡️" }],
          ["a la izquierda", "to the left", "phrase", { freq: 900, emoji: "⬅️" }],
          ["todo recto", "straight ahead", "phrase", { freq: 1500, region: "Spain & much of Latin America (Mexico: todo derecho)", keys: ["todo recto", "todo derecho"], alt: ["straight on"] }],
          ["la calle", "the street", "noun", { g: "f", freq: 250 }],
          ["la esquina", "the corner", "noun", { g: "f", freq: 1400 }],
          ["doblar", "to turn", "verb", { freq: 1800, alt: ["to turn"] }],
          ["seguir", "to continue, to follow", "verb", { freq: 200, alt: ["to keep going", "to follow"] }],
          ["¿cómo llego a…?", "how do I get to…?", "question", { freq: 900, keys: ["cómo llego"] }],
          ["el museo", "the museum", "noun", { g: "m", freq: 1200, emoji: "🏛️" }],
          ["al lado de", "next to", "phrase", { freq: 900, keys: ["al lado"] }],
          ["al", "to the (a + el)", "function", { freq: 15 }],
          ["del", "of the (de + el)", "function", { freq: 12 }],
        ],
        sentences: [
          ["¿Cómo llego al museo?", "How do I get to the museum?", { note: "A + el always contracts to al.", c: ["al-del"] }],
          ["Sigue todo recto.", "Keep going straight.", { alt: ["Siga todo recto.", "Sigue todo derecho.", "Siga todo derecho."], altEn: ["Go straight ahead.", "Continue straight ahead.", "Keep going straight ahead."] }],
          ["Dobla a la derecha.", "Turn right.", { alt: ["Doble a la derecha.", "Gira a la derecha."], altEn: ["Turn to the right."] }],
          ["Está a la izquierda.", "It's on the left.", { altEn: ["It is on the left.", "It's to the left."] }],
          ["Está en la esquina.", "It's on the corner.", { altEn: ["It is on the corner.", "It's at the corner."] }],
          ["El banco está al lado del hotel.", "The bank is next to the hotel.", { altEn: ["The bank is beside the hotel."], note: "De + el contracts to del.", c: ["al-del"] }],
        ],
        concepts: ["al-del"],
        speaking: [
          [1, "Dobla a la derecha y sigue todo recto.", "Turn right and keep going straight.", "Dobla a la derecha y sigue todo recto.", "Turn right and keep going straight.", ["derecha", "recto|derecho"], { model: "Dobla a la derecha y sigue todo recto." }],
          [4, "Ask how to get to the museum.", "", "¿Cómo llego al museo?", "How do I get to the museum?", ["como llego|donde esta|dónde está", "museo"]],
        ],
      },
      {
        title: "Transportation",
        titleEs: "El transporte",
        goal: "Say how you get around.",
        vocab: [
          ["ir", "to go", "verb", { freq: 16 }],
          ["el autobús", "the bus", "noun", { g: "m", freq: 1300, emoji: "🚌", keys: ["autobús", "autobuses", "camión", "colectivo"], region: "Many names by region (Mexico: el camión; Argentina: el colectivo)" }],
          ["el metro", "the subway, the metro", "noun", { g: "m", freq: 1400, emoji: "🚇", alt: ["the subway", "the metro"] }],
          ["el tren", "the train", "noun", { g: "m", freq: 900, emoji: "🚆" }],
          ["el carro", "the car", "noun", { g: "m", freq: 900, emoji: "🚗", region: "Latin America (Spain: el coche)", keys: ["carro", "carros", "coche", "coches", "auto", "autos"] }],
          ["a pie", "on foot", "phrase", { freq: 1500, emoji: "🚶" }],
          ["tomar", "to take", "verb", { freq: 150 }],
          ["la estación", "the station", "noun", { g: "f", freq: 900 }],
          ["el trabajo", "the job, work", "noun", { g: "m", freq: 100, alt: ["work", "the job"] }],
        ],
        sentences: [
          ["Voy al trabajo en metro.", "I go to work by subway.", { altEn: ["I go to work on the subway.", "I take the subway to work.", "I go to work by metro."], note: "“By” a vehicle is en: en metro, en tren, en carro.", c: ["al-del"] }],
          ["Tomo el autobús.", "I take the bus.", { alt: ["Tomo el camión.", "Tomo el colectivo."] }],
          ["¿Vas en tren?", "Are you going by train?", { altEn: ["Do you go by train?", "Are you taking the train?"] }],
          ["Voy a pie.", "I'm walking.", { altEn: ["I go on foot.", "I walk.", "I'm going on foot."] }],
          ["Mi carro es rojo.", "My car is red.", { alt: ["Mi coche es rojo.", "Mi auto es rojo."] }],
          ["¿Dónde está la estación de tren?", "Where is the train station?", { altEn: ["Where's the train station?"] }],
        ],
        speaking: [
          [1, "Voy al trabajo en autobús.", "I go to work by bus.", "Voy al trabajo en autobús.", "I go to work by bus.", ["voy", "trabajo"], { model: "Voy al trabajo en autobús." }],
          [3, "¿Cómo vas al trabajo o a la escuela?", "How do you get to work or school?", "Voy en metro.", "I go by subway.", ["voy|tomo", "metro|autobus|autobús|tren|carro|coche|pie|bicicleta|camion|camión"]],
        ],
      },
      {
        title: "Going to…",
        titleEs: "Voy a…",
        goal: "Talk about what you're going to do.",
        minutes: 7,
        vocab: [
          ["ir a + infinitivo", "going to (do something)", "phrase", { freq: 300, keys: ["voy a", "vas a", "va a", "vamos a", "van a"] }],
          ["esta noche", "tonight", "phrase", { freq: 500 }],
          ["visitar", "to visit", "verb", { freq: 700 }],
          ["llegar", "to arrive", "verb", { freq: 180 }],
          ["la playa", "the beach", "noun", { g: "f", freq: 900, emoji: "🏖️" }],
          ["el cine", "the movie theater", "noun", { g: "m", freq: 1200, emoji: "🎬", alt: ["the cinema", "the movies"] }],
        ],
        sentences: [
          ["Mañana voy a ir al supermercado.", "Tomorrow I'm going to go to the supermarket.", { alt: ["Mañana voy al supermercado."], altEn: ["Tomorrow I'm going to the supermarket.", "Tomorrow I am going to go to the supermarket.", "I'm going to go to the supermarket tomorrow."], note: "Voy a + infinitive = going to do. Here the infinitive is ir: voy a ir.", c: ["ir-a", "al-del"] }],
          ["Voy a comer con mi amiga.", "I'm going to eat with my friend.", { altEn: ["I am going to eat with my friend."], c: ["ir-a"] }],
          ["¿Qué vas a hacer esta noche?", "What are you going to do tonight?", { c: ["ir-a"] }],
          ["Vamos a visitar el museo.", "We're going to visit the museum.", { altEn: ["We are going to visit the museum.", "Let's visit the museum."], c: ["ir-a"] }],
          ["El tren va a llegar tarde.", "The train is going to arrive late.", { altEn: ["The train is going to be late.", "The train will arrive late."], c: ["ir-a"] }],
          ["El sábado vamos a ir a la playa.", "On Saturday we're going to go to the beach.", { alt: ["El sábado vamos a la playa."], altEn: ["On Saturday we are going to the beach.", "We're going to the beach on Saturday."], c: ["ir-a"] }],
        ],
        concepts: ["ir-a"],
        speaking: [
          [1, "Mañana voy a ir al supermercado.", "Tomorrow I'm going to go to the supermarket.", "Mañana voy a ir al supermercado.", "Tomorrow I'm going to go to the supermarket.", ["voy a", "supermercado"], { model: "Mañana voy a ir al supermercado." }],
          [3, "¿Qué vas a hacer esta noche?", "What are you going to do tonight?", "Voy a cenar con mi familia.", "I'm going to have dinner with my family.", ["voy a"]],
          [4, "¿Qué vas a comer mañana?", "What are you going to eat tomorrow?", "Mañana voy a comer pollo con arroz.", "Tomorrow I'm going to eat chicken with rice.", ["voy a", "comer|cenar|desayunar|almorzar"]],
        ],
      },
    ],
  },

  // ─── Unit 6 ────────────────────────────────────────────────────────────
  {
    title: "Shopping",
    description: "Find what you need, describe it, and pay for it.",
    canDo: ["Say what you're looking for", "Describe colors and sizes", "Ask prices and pay", "Buy food at a market"],
    lessons: [
      {
        title: "Buying things",
        titleEs: "Comprar",
        goal: "Say what you need and what you're looking for.",
        vocab: [
          ["comprar", "to buy", "verb", { freq: 350, emoji: "🛍️" }],
          ["necesitar", "to need", "verb", { freq: 250 }],
          ["buscar", "to look for", "verb", { freq: 200 }],
          ["la tienda", "the store, the shop", "noun", { g: "f", freq: 700, emoji: "🏪", alt: ["the store", "the shop"] }],
          ["la ropa", "the clothes", "noun", { g: "f", freq: 800, emoji: "👕", alt: ["clothes", "clothing"] }],
          ["la camisa", "the shirt", "noun", { g: "f", freq: 1500, emoji: "👔" }],
          ["los zapatos", "the shoes", "noun", { g: "m", freq: 1500, emoji: "👟", keys: ["zapatos", "zapato"] }],
          ["este", "this (masculine)", "function", { freq: 35, keys: ["este", "estos"] }],
          ["esta", "this (feminine)", "function", { freq: 35, keys: ["esta", "estas"] }],
        ],
        sentences: [
          ["Necesito comprar ropa.", "I need to buy clothes.", { altEn: ["I need to buy some clothes."] }],
          ["Busco una camisa azul.", "I'm looking for a blue shirt.", { altEn: ["I am looking for a blue shirt."], note: "Buscar already means “look for” — no extra word needed." }],
          ["¿Tienen zapatos negros?", "Do you have black shoes?", { altEn: ["Do you all have black shoes?", "Have you got black shoes?"] }],
          ["Esta camisa es muy bonita.", "This shirt is very pretty.", { altEn: ["This shirt is very nice.", "This shirt is really nice."], c: ["gender"] }],
          ["Quiero comprar este libro.", "I want to buy this book.", { altEn: ["I'd like to buy this book."] }],
          ["La tienda está en el centro.", "The store is downtown.", { altEn: ["The shop is downtown.", "The store is in the center."], c: ["hay-esta"] }],
        ],
        speaking: [
          [1, "Busco una camisa y unos zapatos.", "I'm looking for a shirt and some shoes.", "Busco una camisa y unos zapatos.", "I'm looking for a shirt and some shoes.", ["busco", "camisa"], { model: "Busco una camisa y unos zapatos." }],
          [4, "Tell the clerk what you need to buy.", "", "Necesito comprar unos zapatos.", "I need to buy some shoes.", ["necesito|busco|quiero", "ropa|camisa|zapatos|libro"]],
        ],
      },
      {
        title: "Colors and sizes",
        titleEs: "Colores y tallas",
        goal: "Describe what you want: color and size.",
        vocab: [
          ["rojo", "red", "adjective", { freq: 900, emoji: "🟥" }],
          ["azul", "blue", "adjective", { freq: 900, emoji: "🟦" }],
          ["negro", "black", "adjective", { freq: 800, emoji: "⬛" }],
          ["blanco", "white", "adjective", { freq: 800, emoji: "⬜" }],
          ["verde", "green", "adjective", { freq: 900, emoji: "🟩" }],
          ["grande", "big, large", "adjective", { freq: 150 }],
          ["la talla", "the size (clothing)", "noun", { g: "f", freq: 2500 }],
          ["más", "more", "adverb", { freq: 20 }],
        ],
        sentences: [
          ["¿Tiene esta camisa en azul?", "Do you have this shirt in blue?", { altEn: ["Do you have this shirt in blue?", "Does it come in blue?"], note: "Tiene (usted) is the polite way to address a clerk." }],
          ["Es muy grande.", "It's very big.", { altEn: ["It is too big.", "It's too big.", "It is very big."] }],
          ["Necesito una talla más pequeña.", "I need a smaller size.", { c: ["gender"] }],
          ["Me gustan los zapatos blancos.", "I like the white shoes.", { altEn: ["I like white shoes."], c: ["gustar", "gender"] }],
          ["La casa es verde.", "The house is green."],
          ["Quiero la camisa roja.", "I want the red shirt.", { altEn: ["I'd like the red shirt."], note: "Rojo → roja because camisa is feminine.", c: ["gender"] }],
        ],
        speaking: [
          [3, "¿Qué color te gusta?", "What color do you like?", "Me gusta el azul.", "I like blue.", ["me gusta|prefiero", "rojo|azul|negro|blanco|verde"]],
          [5, "Describe esta imagen.", "Describe this picture.", "Hay una camisa roja y unos zapatos negros.", "There's a red shirt and some black shoes.", ["camisa|zapatos", "roja|rojo|negros|negro|azul|blanca|blanco"], { scene: "👕🟥 👟⬛" }],
        ],
      },
      {
        title: "How much is it?",
        titleEs: "¿Cuánto cuesta?",
        goal: "Ask prices, react to them, and pay.",
        minutes: 7,
        vocab: [
          ["¿cuánto cuesta?", "how much is it?", "question", { freq: 600, keys: ["cuánto cuesta", "cuánto cuestan"], alt: ["how much does it cost"] }],
          ["costar", "to cost", "verb", { freq: 600 }],
          ["el dinero", "the money", "noun", { g: "m", freq: 250, emoji: "💵" }],
          ["el peso", "the peso", "noun", { g: "m", freq: 900 }],
          ["caro", "expensive", "adjective", { freq: 1300 }],
          ["barato", "cheap", "adjective", { freq: 1600 }],
          ["pagar", "to pay", "verb", { freq: 400, emoji: "💳" }],
          ["la tarjeta", "the card", "noun", { g: "f", freq: 900 }],
          ["en efectivo", "in cash", "phrase", { freq: 2500 }],
          ["poder", "to be able to, can", "verb", { freq: 23, alt: ["can", "to be able to"] }],
        ],
        sentences: [
          ["¿Cuánto cuesta?", "How much is it?", { altEn: ["How much does it cost?"], c: ["stem-changing"] }],
          ["¿Cuánto cuestan los zapatos?", "How much are the shoes?", { altEn: ["How much do the shoes cost?"], note: "Plural thing → cuestan.", c: ["stem-changing"] }],
          ["Es muy caro.", "It's very expensive.", { altEn: ["It is very expensive.", "It's too expensive.", "That's very expensive."] }],
          ["Cuesta cincuenta pesos.", "It costs fifty pesos.", { altEn: ["It's fifty pesos."] }],
          ["¿Puedo pagar con tarjeta?", "Can I pay by card?", { altEn: ["Can I pay with a card?", "Can I pay with card?"], c: ["stem-changing"] }],
          ["Pago en efectivo.", "I'll pay in cash.", { altEn: ["I pay in cash.", "I'm paying cash.", "I'll pay cash."] }],
        ],
        speaking: [
          [1, "¿Cuánto cuesta? ¿Puedo pagar con tarjeta?", "How much is it? Can I pay by card?", "¿Cuánto cuesta? ¿Puedo pagar con tarjeta?", "How much is it? Can I pay by card?", ["cuanto|cuánto", "tarjeta"], { model: "¿Cuánto cuesta? ¿Puedo pagar con tarjeta?" }],
          [4, "Ask the price of the shoes.", "", "¿Cuánto cuestan los zapatos?", "How much are the shoes?", ["cuanto|cuánto", "cuestan|cuesta|valen", "zapatos"]],
        ],
      },
      {
        title: "At the market",
        titleEs: "En el mercado",
        goal: "Buy fruit and vegetables by weight.",
        kind: "scenario",
        scenario: "market",
        minutes: 8,
        vocab: [
          ["el mercado", "the market", "noun", { g: "m", freq: 900, emoji: "🧺" }],
          ["el kilo", "the kilo", "noun", { g: "m", freq: 1500 }],
          ["medio", "half", "adjective", { freq: 600 }],
          ["el tomate", "the tomato", "noun", { g: "m", freq: 2000, emoji: "🍅", region: "Mexico also: el jitomate", keys: ["tomate", "tomates", "jitomate", "jitomates"] }],
          ["¿me da…?", "can I have…? (lit. do you give me)", "question", { freq: 800, keys: ["me da", "me das"], alt: ["can I have", "could I have"] }],
          ["aquí tiene", "here you are", "phrase", { freq: 1200, alt: ["here you go"] }],
          ["eso es todo", "that's all", "phrase", { freq: 1200, alt: ["that is all", "that's it"] }],
        ],
        sentences: [
          ["¿Me da un kilo de tomates?", "Can I have a kilo of tomatoes?", { altEn: ["Could I have a kilo of tomatoes?", "Can you give me a kilo of tomatoes?"], alt: ["Me da un kilo de tomates, por favor.", "Un kilo de tomates, por favor."] }],
          ["Medio kilo de naranjas, por favor.", "Half a kilo of oranges, please.", { note: "Medio goes straight before the noun: medio kilo." }],
          ["Aquí tiene.", "Here you are.", { altEn: ["Here you go.", "Here it is."] }],
          ["Eso es todo, gracias.", "That's all, thanks.", { altEn: ["That is all, thank you.", "That's it, thanks."] }],
          ["¿A cómo están las naranjas?", "How much are the oranges?", { altEn: ["What are the oranges going for?"], note: "At markets, ¿a cómo está…? asks today's price." }],
          ["Las manzanas están muy baratas hoy.", "The apples are very cheap today.", { note: "Prices today are a changing state → estar.", c: ["ser-estar"] }],
        ],
        speaking: [
          [1, "¿Me da un kilo de tomates, por favor?", "Can I have a kilo of tomatoes, please?", "¿Me da un kilo de tomates, por favor?", "Can I have a kilo of tomatoes, please?", ["me da", "kilo"], { model: "¿Me da un kilo de tomates, por favor?" }],
          [6, "Buenos días, ¿qué le doy?", "Good morning, what can I get you?", "Medio kilo de naranjas y un kilo de tomates, por favor.", "Half a kilo of oranges and a kilo of tomatoes, please.", ["kilo|medio|quiero|me da|quisiera", "naranja|naranjas|tomate|tomates|manzana|manzanas|fruta"]],
        ],
      },
    ],
  },
];
