// Level 2 — Everyday Spanish (approx. A2).

import type { UnitDef } from "./build";

export const LEVEL2: UnitDef[] = [
  {
    title: "Past Experiences",
    description: "Say what you did yesterday, last weekend and last year.",
    canDo: ["Say what you did yesterday", "Ask someone about their weekend", "Tell a short story in order"],
    lessons: [
      {
        title: "Yesterday I ate…",
        titleEs: "Ayer comí…",
        goal: "See the past tense in action and use your first past forms.",
        minutes: 8,
        vocab: [
          ["ayer", "yesterday", "adverb", { freq: 300, def: "el día antes de hoy" }],
          ["anoche", "last night", "adverb", { freq: 900 }],
          ["comí", "I ate", "verb", { freq: 900, keys: ["comí", "comiste", "comió", "comimos", "comieron"], lemma: "comer" }],
          ["fui", "I went / I was", "verb", { freq: 300, keys: ["fui", "fuiste", "fue", "fuimos", "fueron"], lemma: "ir" }],
          ["vi", "I saw", "verb", { freq: 500, keys: ["vi", "viste", "vio", "vimos", "vieron"], lemma: "ver" }],
          ["la película", "the movie", "noun", { g: "f", freq: 700, emoji: "🎞️", alt: ["the film"] }],
          ["la pizza", "the pizza", "noun", { g: "f", freq: 2000, emoji: "🍕" }],
          ["la semana pasada", "last week", "phrase", { freq: 900 }],
          ["¿adónde?", "where (to)?", "question", { freq: 900, keys: ["adónde"] }],
        ],
        sentences: [
          ["Ayer comí pizza.", "Yesterday I ate pizza.", { altEn: ["I ate pizza yesterday.", "Yesterday I had pizza."], alt: ["Ayer yo comí pizza."], note: "Comer → comí: -er verbs take -í for “I” in the past.", starter: "Ayer comí…", c: ["preterite"] }],
          ["Ayer fui al cine.", "Yesterday I went to the movies.", { altEn: ["I went to the movies yesterday.", "Yesterday I went to the cinema.", "Yesterday I went to the movie theater."], note: "Fui is the past of ir (and of ser!).", c: ["preterite"] }],
          ["Anoche vi una película.", "Last night I watched a movie.", { altEn: ["Last night I saw a movie.", "I watched a movie last night.", "I saw a film last night."], c: ["preterite"] }],
          ["¿Qué comiste ayer?", "What did you eat yesterday?", { c: ["preterite"] }],
          ["La semana pasada fui a la playa.", "Last week I went to the beach.", { altEn: ["I went to the beach last week."], c: ["preterite"] }],
          ["¿Adónde fuiste ayer?", "Where did you go yesterday?", { alt: ["¿A dónde fuiste ayer?", "¿Dónde fuiste ayer?"], c: ["preterite"] }],
          ["Ayer no comí nada.", "Yesterday I didn't eat anything.", { altEn: ["I didn't eat anything yesterday.", "Yesterday I ate nothing."], note: "Spanish uses a double negative: no … nada.", c: ["preterite"] }],
        ],
        concepts: ["preterite"],
        speaking: [
          [1, "Ayer comí pizza con mis amigos.", "Yesterday I ate pizza with my friends.", "Ayer comí pizza con mis amigos.", "Yesterday I ate pizza with my friends.", ["ayer", "comi|comí"], { model: "Ayer comí pizza con mis amigos." }],
          [3, "¿Qué comiste ayer?", "What did you eat yesterday?", "Ayer comí arroz con pollo.", "Yesterday I ate chicken and rice.", ["comi|comí"], { starter: "Ayer comí…" }],
          [4, "¿Qué hiciste hoy?", "What did you do today?", "Hoy trabajé y después fui al supermercado.", "Today I worked and then I went to the supermarket.", ["fui|comi|comí|trabaje|trabajé|estudie|estudié|hable|hablé|vi|hice|sali|salí|lei|leí"]],
        ],
      },
      {
        title: "What did you do?",
        titleEs: "¿Qué hiciste?",
        goal: "Talk about your weekend with regular and irregular past forms.",
        minutes: 8,
        vocab: [
          ["hice", "I did / I made", "verb", { freq: 700, keys: ["hice", "hiciste", "hizo", "hicimos", "hicieron"], lemma: "hacer" }],
          ["trabajé", "I worked", "verb", { freq: 1000, keys: ["trabajé", "trabajaste", "trabajó", "trabajamos", "trabajaron"], lemma: "trabajar" }],
          ["hablé", "I talked / I spoke", "verb", { freq: 1000, keys: ["hablé", "hablaste", "habló", "hablaron"], lemma: "hablar" }],
          ["salir", "to go out, to leave", "verb", { freq: 150 }],
          ["llegué", "I arrived", "verb", { freq: 1200, keys: ["llegué", "llegaste", "llegó", "llegamos", "llegaron"], lemma: "llegar" }],
          ["todo el día", "all day", "phrase", { freq: 900 }],
          ["el fin de semana pasado", "last weekend", "phrase", { freq: 1500 }],
        ],
        sentences: [
          ["¿Qué hiciste el fin de semana?", "What did you do on the weekend?", { altEn: ["What did you do over the weekend?", "What did you do this weekend?", "What did you do at the weekend?"], c: ["preterite"] }],
          ["Trabajé todo el día.", "I worked all day.", { altEn: ["I worked the whole day."], note: "-ar verbs: -é for “I” — the accent matters: trabajé (I worked) vs. trabaje.", c: ["preterite"] }],
          ["Hablé con mi madre.", "I talked to my mother.", { altEn: ["I spoke with my mother.", "I talked with my mom.", "I spoke to my mother."], c: ["preterite"] }],
          ["Salí con mis amigos.", "I went out with my friends.", { c: ["preterite"] }],
          ["Llegué a casa tarde.", "I got home late.", { altEn: ["I arrived home late.", "I came home late."], note: "Llegar → llegué: the u keeps the hard g sound.", c: ["preterite"] }],
          ["Fui a la playa con mis amigos.", "I went to the beach with my friends.", { c: ["preterite"] }],
          ["El fin de semana pasado no hice nada.", "Last weekend I didn't do anything.", { altEn: ["I didn't do anything last weekend.", "Last weekend I did nothing."], c: ["preterite"] }],
        ],
        concepts: ["preterite"],
        speaking: [
          [3, "¿Qué hiciste el fin de semana?", "What did you do on the weekend?", "Fui a la playa con mis amigos.", "I went to the beach with my friends.", ["fui|hice|sali|salí|comi|comí|trabaje|trabajé|vi|hable|hablé|estudie|estudié"]],
          [4, "Describe lo que hiciste ayer.", "Describe what you did yesterday.", "Ayer trabajé, después cené con mi familia y vi una película.", "Yesterday I worked, then had dinner with my family and watched a movie.", ["fui|hice|sali|salí|comi|comí|trabaje|trabajé|vi|hable|hablé|cene|cené|estudie|estudié", "despues|después|y|luego"]],
        ],
      },
      {
        title: "Telling a story",
        titleEs: "Contar una historia",
        goal: "Put events in order so a story is easy to follow.",
        minutes: 8,
        vocab: [
          ["luego", "then, later", "adverb", { freq: 250 }],
          ["al final", "in the end", "phrase", { freq: 900 }],
          ["entonces", "so, then", "adverb", { freq: 150 }],
          ["de repente", "suddenly", "phrase", { freq: 1500 }],
          ["pasar", "to happen", "verb", { freq: 120 }],
          ["llover", "to rain", "verb", { freq: 1500, emoji: "🌧️" }],
          ["empezar", "to start, to begin", "verb", { freq: 300 }],
          ["llamar", "to call", "verb", { freq: 300, emoji: "📞" }],
        ],
        sentences: [
          ["Primero desayuné, luego fui al trabajo.", "First I had breakfast, then I went to work.", { altEn: ["First I ate breakfast, then I went to work."], c: ["preterite"] }],
          ["¿Qué pasó?", "What happened?", { c: ["preterite"] }],
          ["De repente empezó a llover.", "Suddenly it started to rain.", { altEn: ["Suddenly it began to rain.", "Suddenly it started raining."], c: ["preterite"] }],
          ["Al final llegamos a casa.", "In the end we got home.", { altEn: ["In the end we arrived home.", "Finally we got home."], c: ["preterite"] }],
          ["Entonces llamé a mi hermano.", "So I called my brother.", { altEn: ["Then I called my brother."], note: "A person as object takes a: llamé a mi hermano.", c: ["preterite"] }],
        ],
        speaking: [
          [4, "Cuenta algo que pasó la semana pasada.", "Tell something that happened last week.", "La semana pasada fui al parque. De repente empezó a llover, entonces volví a casa.", "Last week I went to the park. Suddenly it started to rain, so I went back home.", ["fui|paso|pasó|empezo|empezó|llegue|llegué|llame|llamé|vi|comi|comí", "primero|luego|despues|después|entonces|de repente|al final"]],
        ],
      },
    ],
  },
  {
    title: "Making Plans",
    description: "Talk about the future, invite people and respond to invitations.",
    canDo: ["Talk about plans and obligations", "Invite someone", "Accept or decline politely"],
    lessons: [
      {
        title: "Plans",
        titleEs: "Los planes",
        goal: "Talk about what you have to do and plan to do.",
        vocab: [
          ["tener que", "to have to", "phrase", { freq: 150, keys: ["tengo que", "tienes que", "tiene que", "tenemos que", "tienen que"] }],
          ["pensar", "to think, to plan", "verb", { freq: 180 }],
          ["próximo", "next", "adjective", { freq: 500 }],
          ["el plan", "the plan", "noun", { g: "m", freq: 700 }],
          ["viajar", "to travel", "verb", { freq: 800, emoji: "✈️" }],
          ["los abuelos", "the grandparents", "noun", { g: "m", freq: 1200, keys: ["abuelos", "abuelo", "abuela", "abuelas"] }],
        ],
        sentences: [
          ["Tengo que trabajar mañana.", "I have to work tomorrow.", { note: "Tener que + infinitive = have to.", c: ["tener-que"] }],
          ["El próximo año quiero viajar a España.", "Next year I want to travel to Spain.", { altEn: ["I want to travel to Spain next year."] }],
          ["¿Tienes planes para el sábado?", "Do you have plans for Saturday?", { altEn: ["Have you got plans for Saturday?", "Do you have any plans for Saturday?"] }],
          ["Pienso visitar a mis abuelos.", "I'm planning to visit my grandparents.", { altEn: ["I plan to visit my grandparents.", "I'm thinking of visiting my grandparents."], note: "Pensar + infinitive = to plan to." }],
          ["No tengo planes.", "I don't have plans.", { altEn: ["I have no plans.", "I don't have any plans."] }],
          ["Tenemos que llegar temprano.", "We have to arrive early.", { altEn: ["We have to get there early."], c: ["tener-que"] }],
        ],
        concepts: ["tener-que"],
        speaking: [
          [3, "¿Qué tienes que hacer mañana?", "What do you have to do tomorrow?", "Mañana tengo que trabajar y estudiar.", "Tomorrow I have to work and study.", ["tengo que"]],
          [4, "¿Qué planes tienes para el fin de semana?", "What plans do you have for the weekend?", "Voy a visitar a mis abuelos y pienso ir al cine.", "I'm going to visit my grandparents and I plan to go to the movies.", ["voy a|pienso|quiero|tengo que"]],
        ],
      },
      {
        title: "Meeting up",
        titleEs: "Quedar con amigos",
        goal: "Invite a friend, agree on a time, or say no politely.",
        kind: "scenario",
        scenario: "plans",
        minutes: 8,
        vocab: [
          ["¿quieres ir…?", "do you want to go…?", "question", { freq: 600, keys: ["quieres ir"] }],
          ["claro", "of course, sure", "interjection", { freq: 200, alt: ["sure", "of course"] }],
          ["qué buena idea", "what a good idea", "phrase", { freq: 1500, alt: ["great idea", "good idea"] }],
          ["lo siento", "I'm sorry", "phrase", { freq: 300, alt: ["sorry", "I am sorry"] }],
          ["¿te parece?", "does that work for you?", "question", { freq: 900, keys: ["te parece"], alt: ["how does that sound"] }],
          ["nos vemos", "see you", "phrase", { freq: 600 }],
        ],
        sentences: [
          ["¿Quieres ir al cine el viernes?", "Do you want to go to the movies on Friday?", { altEn: ["Would you like to go to the movies on Friday?", "Do you want to go to the cinema on Friday?"] }],
          ["¡Claro! ¿A qué hora?", "Sure! What time?", { altEn: ["Of course! At what time?", "Sure! At what time?"] }],
          ["Lo siento, no puedo.", "I'm sorry, I can't.", { altEn: ["Sorry, I can't.", "I am sorry, I cannot."] }],
          ["¿Te parece bien a las ocho?", "Does eight o'clock work for you?", { altEn: ["Is eight okay with you?", "How about at eight?", "Is eight o'clock good for you?"] }],
          ["Nos vemos mañana.", "See you tomorrow."],
          ["¡Qué buena idea!", "What a good idea!", { altEn: ["What a great idea!", "Great idea!"] }],
        ],
        speaking: [
          [6, "¿Quieres ir al cine el viernes?", "Do you want to go to the movies on Friday?", "¡Claro! ¿A qué hora?", "Sure! What time?", ["claro|si|sí|no puedo|lo siento|vale|bueno"]],
          [4, "Invita a un amigo a comer el sábado.", "Invite a friend to eat on Saturday.", "¿Quieres comer conmigo el sábado?", "Do you want to eat with me on Saturday?", ["quieres|vamos", "comer|almorzar|cenar"]],
        ],
      },
    ],
  },
  {
    title: "Opinions",
    description: "Say what you think, agree, disagree and compare.",
    canDo: ["Give a simple opinion", "Agree and disagree", "Compare two things"],
    lessons: [
      {
        title: "I think that…",
        titleEs: "Creo que…",
        goal: "Share opinions and react to other people's.",
        vocab: [
          ["creo que", "I think that", "phrase", { freq: 200, keys: ["creo que"] }],
          ["me parece", "it seems to me", "phrase", { freq: 500, keys: ["me parece"], alt: ["I think", "it seems"] }],
          ["estar de acuerdo", "to agree", "phrase", { freq: 600, keys: ["de acuerdo"] }],
          ["depende", "it depends", "phrase", { freq: 900 }],
          ["interesante", "interesting", "adjective", { freq: 700 }],
          ["aburrido", "boring", "adjective", { freq: 1400, emoji: "🥱" }],
          ["la idea", "the idea", "noun", { g: "f", freq: 300, emoji: "💡" }],
          ["bueno", "good", "adjective", { freq: 60, keys: ["bueno", "buena", "buenos", "buenas", "buen"] }],
        ],
        sentences: [
          ["Creo que es una buena idea.", "I think it's a good idea.", { altEn: ["I think that it's a good idea.", "I think that is a good idea."], c: ["opinions"] }],
          ["Me parece interesante.", "I think it's interesting.", { altEn: ["It seems interesting to me.", "It seems interesting.", "I find it interesting."], c: ["opinions"] }],
          ["No estoy de acuerdo.", "I don't agree.", { altEn: ["I disagree.", "I do not agree."], note: "Agreeing is a state → estar de acuerdo.", c: ["opinions"] }],
          ["Depende.", "It depends."],
          ["Creo que sí.", "I think so.", { c: ["opinions"] }],
          ["La película fue muy aburrida.", "The movie was very boring.", { altEn: ["The film was really boring."], c: ["preterite"] }],
        ],
        concepts: ["opinions"],
        speaking: [
          [3, "¿Te gusta aprender español?", "Do you like learning Spanish?", "Sí, me parece muy interesante.", "Yes, I find it very interesting.", ["me gusta|me parece|creo que|si|sí|no"]],
          [4, "¿Qué piensas de tu ciudad?", "What do you think of your city?", "Creo que mi ciudad es bonita, pero es muy cara.", "I think my city is pretty, but it's very expensive.", ["creo que|me parece|pienso que|en mi opinion|en mi opinión"]],
        ],
      },
      {
        title: "I prefer…",
        titleEs: "Prefiero…",
        goal: "Compare things and say which you prefer.",
        vocab: [
          ["preferir", "to prefer", "verb", { freq: 700 }],
          ["mejor", "better, best", "adjective", { freq: 150, keys: ["mejor", "mejores"] }],
          ["peor", "worse, worst", "adjective", { freq: 700, keys: ["peor", "peores"] }],
          ["favorito", "favorite", "adjective", { freq: 1300 }],
          ["la pasta", "the pasta", "noun", { g: "f", freq: 2500, emoji: "🍝" }],
        ],
        sentences: [
          ["Prefiero el café.", "I prefer coffee.", { note: "Preferir: e → ie (prefiero).", c: ["stem-changing"] }],
          ["El té es mejor que el café.", "Tea is better than coffee.", { c: ["comparisons"] }],
          ["Mi comida favorita es la pasta.", "My favorite food is pasta.", { c: ["gender"] }],
          ["Madrid es más grande que Sevilla.", "Madrid is bigger than Seville.", { alt: ["Madrid es más grande que Sevilla"], note: "Más + adjective + que = -er than.", c: ["comparisons"] }],
          ["Esta película es peor.", "This movie is worse.", { altEn: ["This film is worse."], c: ["comparisons"] }],
        ],
        concepts: ["comparisons"],
        speaking: [
          [3, "¿Prefieres el café o el té?", "Do you prefer coffee or tea?", "Prefiero el café, pero me gusta el té también.", "I prefer coffee, but I like tea too.", ["prefiero|me gusta"]],
          [4, "Compara dos ciudades que conoces.", "Compare two cities you know.", "Chicago es más grande que Denver, pero Denver es más tranquilo.", "Chicago is bigger than Denver, but Denver is calmer.", ["mas|más|menos|mejor|peor", "que"]],
        ],
      },
    ],
  },
  {
    title: "Descriptions",
    description: "Describe people, places and homes in more detail.",
    canDo: ["Describe someone's appearance and personality", "Describe your home and town"],
    lessons: [
      {
        title: "What is she like?",
        titleEs: "¿Cómo es?",
        goal: "Describe what people look like and what they're like.",
        vocab: [
          ["el pelo", "the hair", "noun", { g: "m", freq: 900 }],
          ["los ojos", "the eyes", "noun", { g: "m", freq: 400, keys: ["ojos", "ojo"], emoji: "👀" }],
          ["largo", "long", "adjective", { freq: 500 }],
          ["corto", "short (length)", "adjective", { freq: 900 }],
          ["moreno", "dark-haired, tan", "adjective", { freq: 1800 }],
          ["divertido", "fun, funny", "adjective", { freq: 1400, alt: ["fun", "funny"] }],
          ["inteligente", "intelligent, smart", "adjective", { freq: 900, alt: ["smart"] }],
          ["el profesor", "the teacher (male)", "noun", { g: "m", freq: 500, keys: ["profesor", "profesora", "profesores"], alt: ["the teacher", "the professor"] }],
        ],
        sentences: [
          ["Mi hermana tiene el pelo largo.", "My sister has long hair.", { note: "Spanish uses tener + el pelo… for hair and eyes.", c: ["tener-expressions"] }],
          ["Tiene los ojos verdes.", "She has green eyes.", { altEn: ["He has green eyes.", "He's got green eyes.", "She's got green eyes."] }],
          ["Es muy divertido.", "He's a lot of fun.", { altEn: ["He's very funny.", "It's very fun.", "He is very funny.", "He's very fun."] }],
          ["Mi amigo es alto y moreno.", "My friend is tall and dark-haired.", { c: ["ser-estar"] }],
          ["¿Cómo es tu profesor?", "What's your teacher like?", { altEn: ["What is your teacher like?"], note: "¿Cómo es? asks what someone is like; ¿cómo está? asks how they are.", c: ["ser-estar"] }],
        ],
        speaking: [
          [4, "Describe a tu mejor amigo o amiga.", "Describe your best friend.", "Mi mejor amiga es alta, tiene el pelo largo y es muy divertida.", "My best friend is tall, has long hair and is very funny.", ["es", "tiene|pelo|ojos|alto|alta|divertido|divertida|simpatico|simpático|simpatica|simpática|inteligente"]],
        ],
      },
      {
        title: "Home and town",
        titleEs: "La casa y la ciudad",
        goal: "Describe where you live.",
        vocab: [
          ["la ciudad", "the city", "noun", { g: "f", freq: 150, emoji: "🏙️" }],
          ["el pueblo", "the town, the village", "noun", { g: "m", freq: 600 }],
          ["tranquilo", "calm, quiet", "adjective", { freq: 900 }],
          ["el apartamento", "the apartment", "noun", { g: "m", freq: 1500, region: "Latin America (Spain: el piso)", keys: ["apartamento", "apartamentos", "departamento", "piso"] }],
          ["la cocina", "the kitchen", "noun", { g: "f", freq: 1200 }],
          ["el cuarto", "the room, the bedroom", "noun", { g: "m", freq: 900, keys: ["cuarto", "cuartos", "habitación", "habitaciones", "dormitorio"] }],
          ["pero", "but", "function", { freq: 20 }],
        ],
        sentences: [
          ["Vivo en una ciudad muy grande.", "I live in a very big city."],
          ["Mi pueblo es muy tranquilo.", "My town is very quiet.", { altEn: ["My town is very calm.", "My village is very quiet."] }],
          ["El apartamento tiene dos cuartos.", "The apartment has two bedrooms.", { alt: ["El apartamento tiene dos habitaciones.", "El piso tiene dos habitaciones."], altEn: ["The apartment has two rooms."] }],
          ["La cocina es pequeña pero bonita.", "The kitchen is small but nice.", { altEn: ["The kitchen is small but pretty."], c: ["gender"] }],
          ["Mi casa está cerca del parque.", "My house is near the park.", { altEn: ["My house is close to the park."], c: ["al-del", "hay-esta"] }],
        ],
        speaking: [
          [4, "Describe tu casa o tu apartamento.", "Describe your house or apartment.", "Vivo en un apartamento pequeño. Tiene dos cuartos y una cocina bonita.", "I live in a small apartment. It has two bedrooms and a nice kitchen.", ["vivo|tiene|es|hay", "casa|apartamento|cuarto|cuartos|cocina|habitacion|habitación"]],
        ],
      },
    ],
  },
  {
    title: "Work and School",
    description: "Talk about your job, your classes and your responsibilities.",
    canDo: ["Say what you do for work", "Talk about classes and exams", "Describe your schedule"],
    lessons: [
      {
        title: "At work",
        titleEs: "El trabajo",
        goal: "Explain what you do and describe your workday.",
        vocab: [
          ["la oficina", "the office", "noun", { g: "f", freq: 700, emoji: "🏢" }],
          ["el jefe", "the boss", "noun", { g: "m", freq: 900, keys: ["jefe", "jefa", "jefes"] }],
          ["la reunión", "the meeting", "noun", { g: "f", freq: 700, keys: ["reunión", "reuniones"] }],
          ["amable", "kind", "adjective", { freq: 1300 }],
          ["la enfermera", "the nurse", "noun", { g: "f", freq: 2000, keys: ["enfermera", "enfermero", "enfermeras", "enfermeros"] }],
          ["desde casa", "from home", "phrase", { freq: 1500 }],
        ],
        sentences: [
          ["Trabajo como enfermera.", "I work as a nurse.", { alt: ["Trabajo como enfermero.", "Soy enfermera.", "Soy enfermero."], note: "No article after como or soy for jobs: soy enfermera." }],
          ["Tengo una reunión a las diez.", "I have a meeting at ten.", { c: ["telling-time"] }],
          ["Mi jefe es muy amable.", "My boss is very kind.", { altEn: ["My boss is very nice."] }],
          ["¿En qué trabajas?", "What do you do for work?", { altEn: ["What do you do?", "What's your job?", "What is your job?"] }],
          ["Trabajo desde casa los viernes.", "I work from home on Fridays."],
        ],
        speaking: [
          [3, "¿En qué trabajas?", "What do you do for work?", "Trabajo como ingeniero en una oficina.", "I work as an engineer in an office.", ["trabajo|soy|estudio"]],
          [4, "Describe un día normal de trabajo o de clases.", "Describe a normal work or school day.", "Llego a la oficina a las nueve, tengo reuniones y almuerzo a la una.", "I get to the office at nine, have meetings and have lunch at one.", ["llego|trabajo|tengo|estudio|almuerzo|empiezo", "a las|a la|despues|después|luego"]],
        ],
      },
      {
        title: "At school",
        titleEs: "La escuela",
        goal: "Talk about classes, homework and exams.",
        vocab: [
          ["la clase", "the class", "noun", { g: "f", freq: 400 }],
          ["el examen", "the exam", "noun", { g: "m", freq: 1200, keys: ["examen", "exámenes"] }],
          ["la tarea", "the homework", "noun", { g: "f", freq: 1500, alt: ["homework"] }],
          ["aprender", "to learn", "verb", { freq: 400 }],
          ["difícil", "difficult", "adjective", { freq: 500, keys: ["difícil", "difíciles"], alt: ["hard"] }],
          ["fácil", "easy", "adjective", { freq: 700, keys: ["fácil", "fáciles"] }],
          ["explicar", "to explain", "verb", { freq: 700 }],
          ["la historia", "history, story", "noun", { g: "f", freq: 300, alt: ["history", "the story"] }],
        ],
        sentences: [
          ["Tengo un examen mañana.", "I have an exam tomorrow.", { altEn: ["I have a test tomorrow."] }],
          ["La clase de historia es difícil.", "History class is difficult.", { altEn: ["The history class is hard.", "History class is hard."] }],
          ["Aprendo mucho en esta clase.", "I learn a lot in this class."],
          ["No hice la tarea.", "I didn't do the homework.", { altEn: ["I didn't do my homework."], c: ["preterite"] }],
          ["La profesora explica muy bien.", "The teacher explains very well.", { altEn: ["The professor explains things very well."] }],
        ],
        speaking: [
          [4, "¿Qué clase es fácil y qué clase es difícil para ti?", "Which class is easy and which is hard for you?", "La clase de matemáticas es difícil, pero la clase de arte es fácil.", "Math class is hard, but art class is easy.", ["clase|español|espanol|matematicas|matemáticas|historia", "facil|fácil|dificil|difícil"]],
        ],
      },
    ],
  },
  {
    title: "Free Time and Travel",
    description: "Talk about hobbies, how often you do things, and travel plans.",
    canDo: ["Talk about hobbies and frequency", "Handle basic travel situations"],
    lessons: [
      {
        title: "Hobbies",
        titleEs: "Los pasatiempos",
        goal: "Say what you do in your free time and how often.",
        vocab: [
          ["jugar", "to play", "verb", { freq: 400, emoji: "⚽" }],
          ["el fútbol", "soccer", "noun", { g: "m", freq: 900, keys: ["fútbol"], alt: ["football"] }],
          ["bailar", "to dance", "verb", { freq: 1300, emoji: "💃" }],
          ["cocinar", "to cook", "verb", { freq: 1500, emoji: "🍳" }],
          ["la música", "the music", "noun", { g: "f", freq: 500, emoji: "🎵" }],
          ["escuchar", "to listen (to)", "verb", { freq: 400, emoji: "🎧" }],
          ["el tiempo libre", "free time", "noun", { g: "m", freq: 1300, keys: ["tiempo libre"] }],
          ["a veces", "sometimes", "phrase", { freq: 400 }],
          ["siempre", "always", "adverb", { freq: 100 }],
          ["nunca", "never", "adverb", { freq: 200 }],
        ],
        sentences: [
          ["En mi tiempo libre, leo mucho.", "In my free time, I read a lot."],
          ["Juego al fútbol los sábados.", "I play soccer on Saturdays.", { alt: ["Juego fútbol los sábados."], note: "Jugar: u → ue. Many regions say jugar al fútbol; others jugar fútbol.", c: ["stem-changing"] }],
          ["A veces cocino para mis amigos.", "Sometimes I cook for my friends."],
          ["Nunca bailo.", "I never dance.", { alt: ["No bailo nunca."] }],
          ["¿Qué te gusta hacer?", "What do you like to do?", { altEn: ["What do you like doing?"], c: ["gustar"] }],
          ["Siempre escucho música en el autobús.", "I always listen to music on the bus.", { note: "Escuchar already includes “to” — no extra word." }],
        ],
        speaking: [
          [3, "¿Qué te gusta hacer en tu tiempo libre?", "What do you like to do in your free time?", "Me gusta leer y a veces juego al fútbol.", "I like to read and sometimes I play soccer.", ["me gusta|juego|leo|cocino|bailo|escucho|veo"]],
          [4, "¿Con qué frecuencia haces deporte?", "How often do you exercise?", "Juego al fútbol dos veces por semana.", "I play soccer twice a week.", ["siempre|a veces|nunca|veces|todos los dias|todos los días|los"]],
        ],
      },
      {
        title: "Travel",
        titleEs: "Viajar",
        goal: "Get through the airport and check in at a hotel.",
        kind: "scenario",
        scenario: "hotel",
        minutes: 8,
        vocab: [
          ["el avión", "the plane", "noun", { g: "m", freq: 1200, emoji: "✈️", keys: ["avión", "aviones"] }],
          ["el aeropuerto", "the airport", "noun", { g: "m", freq: 1500 }],
          ["el pasaporte", "the passport", "noun", { g: "m", freq: 2500, emoji: "🛂" }],
          ["la maleta", "the suitcase", "noun", { g: "f", freq: 2500, emoji: "🧳" }],
          ["el nombre", "the name", "noun", { g: "m", freq: 200 }],
          ["la reserva", "the reservation", "noun", { g: "f", freq: 2000, alt: ["the booking"] }],
          ["reservar", "to book, to reserve", "verb", { freq: 2500 }],
          ["la habitación", "the room (hotel)", "noun", { g: "f", freq: 800, keys: ["habitación", "habitaciones", "cuarto"] }],
          ["el boleto", "the ticket", "noun", { g: "m", freq: 2000, region: "Latin America (Spain: el billete)", keys: ["boleto", "boletos", "billete", "billetes", "pasaje", "pasajes"] }],
        ],
        sentences: [
          ["¿Dónde está mi pasaporte?", "Where is my passport?", { altEn: ["Where's my passport?"] }],
          ["El avión sale a las seis.", "The plane leaves at six.", { altEn: ["The plane departs at six.", "The flight leaves at six."], c: ["telling-time"] }],
          ["Quiero reservar una habitación.", "I want to book a room.", { altEn: ["I'd like to book a room.", "I want to reserve a room."], alt: ["Quisiera reservar una habitación."] }],
          ["Tengo dos maletas.", "I have two suitcases.", { altEn: ["I've got two suitcases.", "I have two bags."] }],
          ["Necesito un boleto a Madrid.", "I need a ticket to Madrid.", { alt: ["Necesito un billete a Madrid.", "Necesito un boleto para Madrid.", "Necesito un billete para Madrid."] }],
          ["Tengo una reserva a nombre de García.", "I have a reservation under the name García.", { altEn: ["I have a reservation under García.", "I have a booking under the name García."] }],
        ],
        speaking: [
          [6, "Buenas noches, bienvenido al hotel. ¿Tiene una reserva?", "Good evening, welcome to the hotel. Do you have a reservation?", "Sí, tengo una reserva a nombre de {name}.", "Yes, I have a reservation under the name {name}.", ["si|sí|tengo|no", "reserva|nombre|habitacion|habitación"]],
        ],
      },
    ],
  },
];
