// Comprehensible input: short, level-appropriate audio pieces.
// The app computes how much of each piece the learner already knows.

import type { ListeningPiece } from "../engine/types";

export const LISTENING: ListeningPiece[] = [
  {
    id: "me-presento",
    title: "Me presento",
    kind: "description",
    level: 1,
    speed: "slow",
    minutes: 1,
    summary: "Ana introduces herself.",
    requiresLesson: "u1-l3",
    lines: [
      { es: "Hola, buenos días.", en: "Hello, good morning." },
      { es: "Me llamo Ana.", en: "My name is Ana." },
      { es: "Soy de México, pero vivo en Chicago.", en: "I'm from Mexico, but I live in Chicago." },
      { es: "Hablo español y un poco de inglés.", en: "I speak Spanish and a little English." },
      { es: "Hoy estoy muy bien.", en: "Today I'm very well." },
      { es: "Mucho gusto.", en: "Nice to meet you." },
    ],
    questions: [
      { q: "Where is Ana from?", options: ["Mexico", "Chicago", "Spain"], answer: 0 },
      { q: "Where does she live now?", options: ["Mexico City", "Chicago", "Madrid"], answer: 1 },
      { q: "How is she today?", options: ["Tired", "Very well", "So-so"], answer: 1 },
    ],
  },
  {
    id: "en-la-cafeteria",
    title: "En la cafetería",
    kind: "dialogue",
    level: 1,
    speed: "slow",
    minutes: 1,
    summary: "Two friends order at a café.",
    requiresLesson: "u3-l3",
    lines: [
      { speaker: "Luis", es: "Hola, Marta. ¿Qué tal?", en: "Hi, Marta. How's it going?" },
      { speaker: "Marta", es: "Bien, gracias. Tengo mucha sed.", en: "Good, thanks. I'm really thirsty." },
      { speaker: "Luis", es: "¿Quieres un café?", en: "Do you want a coffee?" },
      { speaker: "Marta", es: "No, quiero un jugo de naranja.", en: "No, I want an orange juice." },
      { speaker: "Luis", es: "Yo quiero un café con leche, sin azúcar.", en: "I want a coffee with milk, no sugar." },
      { speaker: "Marta", es: "¿Tienes hambre?", en: "Are you hungry?" },
      { speaker: "Luis", es: "Sí, un poco. Quiero pan con queso.", en: "Yes, a little. I want bread with cheese." },
    ],
    questions: [
      { q: "What does Marta order?", options: ["A coffee", "An orange juice", "Water"], answer: 1 },
      { q: "How does Luis take his coffee?", options: ["With milk, no sugar", "Black with sugar", "With milk and sugar"], answer: 0 },
      { q: "What does Luis want to eat?", options: ["Chicken", "Fruit", "Bread with cheese"], answer: 2 },
    ],
  },
  {
    id: "la-familia-de-lucia",
    title: "La familia de Lucía",
    kind: "description",
    level: 1,
    speed: "slow",
    minutes: 1,
    summary: "Lucía describes her family.",
    requiresLesson: "u2-l4",
    lines: [
      { es: "Me llamo Lucía y tengo veinte años.", en: "My name is Lucía and I'm twenty years old." },
      { es: "Mi familia es pequeña.", en: "My family is small." },
      { es: "Mi madre se llama Rosa y tiene cincuenta años.", en: "My mother's name is Rosa and she's fifty." },
      { es: "Mi padre es de Colombia.", en: "My father is from Colombia." },
      { es: "Tengo un hermano. Se llama Diego.", en: "I have a brother. His name is Diego." },
      { es: "Diego tiene quince años y es muy simpático.", en: "Diego is fifteen and he's very nice." },
    ],
    questions: [
      { q: "How old is Lucía?", options: ["Fifteen", "Twenty", "Fifty"], answer: 1 },
      { q: "Where is her father from?", options: ["Colombia", "Mexico", "Spain"], answer: 0 },
      { q: "What is Diego like?", options: ["Tall", "Tired", "Very nice"], answer: 2 },
    ],
  },
  {
    id: "donde-esta-la-farmacia",
    title: "¿Dónde está la farmacia?",
    kind: "dialogue",
    level: 1,
    speed: "normal",
    minutes: 1,
    summary: "A tourist asks for directions.",
    requiresLesson: "u5-l2",
    lines: [
      { speaker: "Turista", es: "Perdón, ¿hay una farmacia cerca?", en: "Excuse me, is there a pharmacy nearby?" },
      { speaker: "Señora", es: "Sí, hay una en la calle Juárez.", en: "Yes, there's one on Juárez Street." },
      { speaker: "Turista", es: "¿Cómo llego a la calle Juárez?", en: "How do I get to Juárez Street?" },
      { speaker: "Señora", es: "Sigue todo recto y dobla a la derecha.", en: "Go straight ahead and turn right." },
      { speaker: "Señora", es: "La farmacia está en la esquina, al lado del banco.", en: "The pharmacy is on the corner, next to the bank." },
      { speaker: "Turista", es: "¿Está lejos?", en: "Is it far?" },
      { speaker: "Señora", es: "No, está muy cerca. Cinco minutos a pie.", en: "No, it's very close. Five minutes on foot." },
    ],
    questions: [
      { q: "Which way should the tourist turn?", options: ["Left", "Right", "Back"], answer: 1 },
      { q: "What is the pharmacy next to?", options: ["The bank", "The hotel", "The park"], answer: 0 },
      { q: "How far is it?", options: ["Five minutes on foot", "Twenty minutes by bus", "Far away"], answer: 0 },
    ],
  },
  {
    id: "un-dia-normal",
    title: "Un día normal",
    kind: "story",
    level: 1,
    speed: "normal",
    minutes: 2,
    summary: "Carlos walks through his weekday.",
    requiresLesson: "u4-l4",
    lines: [
      { es: "Me llamo Carlos y trabajo en una oficina en el centro.", en: "My name is Carlos and I work in an office downtown." },
      { es: "Me levanto a las seis y media.", en: "I get up at six thirty." },
      { es: "Primero me ducho y después desayuno café con pan.", en: "First I shower and then I have coffee and bread for breakfast." },
      { es: "Voy al trabajo en metro.", en: "I go to work by subway." },
      { es: "Almuerzo a la una con mis amigos del trabajo.", en: "I have lunch at one with my friends from work." },
      { es: "Trabajo hasta las cinco de la tarde.", en: "I work until five in the afternoon." },
      { es: "Por la noche ceno con mi familia y leo un libro.", en: "At night I have dinner with my family and read a book." },
      { es: "Me acuesto a las once. ¡Estoy muy cansado!", en: "I go to bed at eleven. I'm very tired!" },
    ],
    questions: [
      { q: "What time does Carlos get up?", options: ["At six", "At six thirty", "At seven thirty"], answer: 1 },
      { q: "How does he get to work?", options: ["By bus", "On foot", "By subway"], answer: 2 },
      { q: "What does he do at night?", options: ["Goes out with friends", "Has dinner and reads", "Works late"], answer: 1 },
    ],
  },
  {
    id: "mensaje-de-voz",
    title: "Un mensaje de voz",
    kind: "voicemail",
    level: 1,
    speed: "normal",
    minutes: 1,
    summary: "A voicemail from a friend about tomorrow.",
    requiresLesson: "u5-l4",
    lines: [
      { speaker: "Sofía", es: "Hola, soy Sofía.", en: "Hi, it's Sofía." },
      { speaker: "Sofía", es: "Mañana voy a ir al mercado a las diez.", en: "Tomorrow I'm going to go to the market at ten." },
      { speaker: "Sofía", es: "¿Quieres venir conmigo?", en: "Do you want to come with me?" },
      { speaker: "Sofía", es: "Después vamos a comer en un restaurante cerca del parque.", en: "Afterwards we're going to eat at a restaurant near the park." },
      { speaker: "Sofía", es: "Voy a tomar el autobús. Llámame esta noche. ¡Adiós!", en: "I'm going to take the bus. Call me tonight. Bye!" },
    ],
    questions: [
      { q: "What time is Sofía going to the market?", options: ["At nine", "At ten", "At two"], answer: 1 },
      { q: "Where will they eat?", options: ["At home", "Near the park", "At the market"], answer: 1 },
      { q: "When should you call her?", options: ["Tonight", "Tomorrow morning", "Now"], answer: 0 },
    ],
  },
  {
    id: "en-el-mercado",
    title: "En el mercado",
    kind: "dialogue",
    level: 1,
    speed: "normal",
    minutes: 1,
    summary: "Shopping for fruit at a market stall.",
    requiresLesson: "u6-l3",
    lines: [
      { speaker: "Vendedor", es: "Buenos días. ¿Qué le doy?", en: "Good morning. What can I get you?" },
      { speaker: "Clienta", es: "¿A cómo están las naranjas?", en: "How much are the oranges?" },
      { speaker: "Vendedor", es: "Están a treinta pesos el kilo. Muy baratas hoy.", en: "Thirty pesos a kilo. Very cheap today." },
      { speaker: "Clienta", es: "Entonces, un kilo de naranjas y medio kilo de tomates.", en: "Then a kilo of oranges and half a kilo of tomatoes." },
      { speaker: "Vendedor", es: "Aquí tiene. ¿Algo más?", en: "Here you are. Anything else?" },
      { speaker: "Clienta", es: "No, eso es todo. ¿Puedo pagar con tarjeta?", en: "No, that's all. Can I pay by card?" },
      { speaker: "Vendedor", es: "Lo siento, solo en efectivo.", en: "Sorry, cash only." },
    ],
    questions: [
      { q: "How much are the oranges per kilo?", options: ["Thirteen pesos", "Thirty pesos", "Three pesos"], answer: 1 },
      { q: "How many tomatoes does she buy?", options: ["Half a kilo", "One kilo", "Two kilos"], answer: 0 },
      { q: "How can she pay?", options: ["By card", "Cash only", "Either"], answer: 1 },
    ],
  },
  {
    id: "el-fin-de-semana-de-diego",
    title: "El fin de semana de Diego",
    kind: "story",
    level: 2,
    speed: "normal",
    minutes: 2,
    summary: "Diego tells what happened last weekend.",
    requiresLesson: "u7-l2",
    lines: [
      { es: "El fin de semana pasado fui a la playa con mis amigos.", en: "Last weekend I went to the beach with my friends." },
      { es: "Llegamos el sábado por la mañana.", en: "We arrived on Saturday morning." },
      { es: "Primero comimos pescado en un restaurante pequeño.", en: "First we ate fish at a small restaurant." },
      { es: "Luego nadamos y jugamos al fútbol en la playa.", en: "Then we swam and played soccer on the beach." },
      { es: "De repente empezó a llover mucho.", en: "Suddenly it started to rain a lot." },
      { es: "Entonces volvimos al hotel y vimos una película.", en: "So we went back to the hotel and watched a movie." },
      { es: "Al final fue un fin de semana muy divertido.", en: "In the end it was a really fun weekend." },
    ],
    questions: [
      { q: "What did they eat first?", options: ["Pizza", "Fish", "Chicken"], answer: 1 },
      { q: "What happened suddenly?", options: ["It started to rain", "They got lost", "The restaurant closed"], answer: 0 },
      { q: "How was the weekend?", options: ["Boring", "Very fun", "Tiring"], answer: 1 },
    ],
  },
  {
    id: "planes-para-el-sabado",
    title: "Planes para el sábado",
    kind: "dialogue",
    level: 2,
    speed: "fast",
    minutes: 1,
    summary: "Two friends make plans — at natural speed.",
    requiresLesson: "u8-l2",
    lines: [
      { speaker: "Pablo", es: "Oye, ¿tienes planes para el sábado?", en: "Hey, do you have plans for Saturday?" },
      { speaker: "Elena", es: "Por la mañana tengo que trabajar, pero por la tarde estoy libre.", en: "In the morning I have to work, but in the afternoon I'm free." },
      { speaker: "Pablo", es: "¿Quieres ir al cine? Hay una película nueva muy buena.", en: "Do you want to go to the movies? There's a really good new movie." },
      { speaker: "Elena", es: "¡Claro! ¿A qué hora empieza?", en: "Sure! What time does it start?" },
      { speaker: "Pablo", es: "A las siete. ¿Te parece bien si nos vemos a las seis y media?", en: "At seven. Is it okay if we meet at six thirty?" },
      { speaker: "Elena", es: "Perfecto. Nos vemos en la entrada del cine.", en: "Perfect. See you at the entrance of the theater." },
    ],
    questions: [
      { q: "When is Elena free?", options: ["Saturday morning", "Saturday afternoon", "Sunday"], answer: 1 },
      { q: "What time does the movie start?", options: ["At six thirty", "At seven", "At eight"], answer: 1 },
      { q: "Where will they meet?", options: ["At a café", "At Elena's house", "At the theater entrance"], answer: 2 },
    ],
  },
  {
    id: "mi-barrio-en-madrid",
    title: "Mi barrio en Madrid",
    kind: "description",
    level: 2,
    speed: "fast",
    minutes: 2,
    summary: "Javier describes his neighborhood — Spain Spanish.",
    requiresLesson: "u10-l2",
    region: "Spain",
    lines: [
      { es: "Vivo en un piso pequeño en el centro de Madrid.", en: "I live in a small apartment in the center of Madrid." },
      { es: "Mi barrio es muy bonito, pero un poco ruidoso.", en: "My neighborhood is very pretty, but a bit noisy." },
      { es: "Hay muchos bares, tiendas y un mercado.", en: "There are lots of bars, shops and a market." },
      { es: "Normalmente voy al trabajo andando, porque está cerca.", en: "I usually walk to work, because it's close." },
      { es: "Los fines de semana quedo con mis amigos para tomar algo.", en: "On weekends I meet up with my friends for a drink." },
      { es: "Creo que es el mejor barrio de la ciudad. ¡Vale la pena visitarlo!", en: "I think it's the best neighborhood in the city. It's worth visiting!" },
    ],
    questions: [
      { q: "What is the neighborhood like?", options: ["Quiet and modern", "Pretty but noisy", "Far from the center"], answer: 1 },
      { q: "How does Javier get to work?", options: ["He walks", "By metro", "By car"], answer: 0 },
      { q: "In Spain, “un piso” here means…", options: ["A floor", "An apartment", "A house"], answer: 1 },
    ],
  },
];
