// Pronunciation training: the sounds English speakers find hardest.

import type { PronunciationModule } from "../engine/types";

const w = (es: string, en: string, syllables: string) => ({ es, en, syllables });

export const PRONUNCIATION: PronunciationModule[] = [
  {
    id: "vowels",
    sound: "a e i o u",
    title: "The five vowels",
    summary: "Spanish vowels are short, clean and never change.",
    tip: "Don't glide. English “no” slides into “noh-oo”; Spanish no stays a pure “o.”",
    mouth: "Keep your jaw steady and cut each vowel off cleanly.",
    words: [w("casa", "house", "ca·sa"), w("mesa", "table", "me·sa"), w("sí", "yes", "sí"), w("todo", "everything", "to·do"), w("uno", "one", "u·no"), w("bueno", "good", "bue·no")],
    contrast: [["mesa", "misa"], ["peso", "piso"], ["todo", "tudo"]],
    sentence: { es: "Ana tiene una mesa en casa.", en: "Ana has a table at home." },
  },
  {
    id: "r-rr",
    sound: "r / rr",
    title: "R and RR",
    summary: "A single r is a quick tap. rr (and r at the start of a word) is a trill.",
    tip: "The tap r sounds like the “tt” in American “butter.” Say “potty” fast → para.",
    mouth: "For rr, relax your tongue behind your top teeth and let the air make it vibrate.",
    words: [w("pero", "but", "pe·ro"), w("perro", "dog", "pe·rro"), w("caro", "expensive", "ca·ro"), w("carro", "car", "ca·rro"), w("rojo", "red", "ro·jo"), w("hora", "hour", "ho·ra")],
    contrast: [["pero", "perro"], ["caro", "carro"], ["cero", "cerro"]],
    sentence: { es: "El perro de Rosa corre rápido.", en: "Rosa's dog runs fast." },
  },
  {
    id: "j",
    sound: "j / ge / gi",
    title: "The J sound",
    summary: "J (and g before e or i) is a breathy sound from the back of the throat.",
    tip: "Like a strong English “h,” or the “ch” in Scottish “loch.”",
    mouth: "Raise the back of your tongue toward the soft palate and push air through.",
    words: [w("jugo", "juice", "ju·go"), w("hijo", "son", "hi·jo"), w("rojo", "red", "ro·jo"), w("gente", "people", "gen·te"), w("jueves", "Thursday", "jue·ves"), w("mujer", "woman", "mu·jer")],
    sentence: { es: "Mi hijo bebe jugo los jueves.", en: "My son drinks juice on Thursdays." },
  },
  {
    id: "enye",
    sound: "ñ",
    title: "The Ñ",
    summary: "Ñ is one sound, like the “ny” in “canyon.”",
    tip: "Año (year) and ano are very different words — make the ñ clear.",
    mouth: "Press the middle of your tongue against the roof of your mouth.",
    words: [w("mañana", "tomorrow", "ma·ña·na"), w("año", "year", "a·ño"), w("España", "Spain", "Es·pa·ña"), w("niño", "boy", "ni·ño"), w("pequeño", "small", "pe·que·ño"), w("baño", "bathroom", "ba·ño")],
    contrast: [["mañana", "manana"], ["año", "ano"]],
    sentence: { es: "Mañana el niño va a España.", en: "Tomorrow the boy is going to Spain." },
  },
  {
    id: "ll-y",
    sound: "ll / y",
    title: "LL and Y",
    summary: "In most regions ll and y sound the same — like the “y” in “yes.”",
    tip: "In Argentina and Uruguay, both sound like “sh” or “zh.” Both are correct.",
    mouth: "Start a “y” with a little more tongue contact than in English.",
    words: [w("llamo", "I call", "lla·mo"), w("calle", "street", "ca·lle"), w("pollo", "chicken", "po·llo"), w("yo", "I", "yo"), w("playa", "beach", "pla·ya"), w("lluvia", "rain", "llu·via")],
    sentence: { es: "Yo me llamo Yolanda y vivo en esta calle.", en: "My name is Yolanda and I live on this street." },
  },
  {
    id: "b-v",
    sound: "b / v",
    title: "B and V",
    summary: "B and V are the same sound in Spanish.",
    tip: "At the start, it's a firm “b.” Between vowels, your lips barely touch — a soft “b.”",
    mouth: "Never use your teeth on the lip as in English “v.”",
    words: [w("vivo", "I live", "vi·vo"), w("beber", "to drink", "be·ber"), w("vaso", "glass", "va·so"), w("bien", "well", "bien"), w("nueve", "nine", "nue·ve"), w("sábado", "Saturday", "sá·ba·do")],
    contrast: [["vaso", "baso"], ["vino", "bino"]],
    sentence: { es: "Vivo en Bogotá y bebo vino el viernes.", en: "I live in Bogotá and drink wine on Friday." },
  },
  {
    id: "d",
    sound: "d",
    title: "The soft D",
    summary: "Between vowels, d softens to a sound like “th” in “this.”",
    tip: "Nada sounds close to “na-tha.” At the start of a word, d is firmer.",
    mouth: "Touch your tongue lightly to the back of your top teeth.",
    words: [w("nada", "nothing", "na·da"), w("todo", "everything", "to·do"), w("cansado", "tired", "can·sa·do"), w("día", "day", "dí·a"), w("ciudad", "city", "ciu·dad"), w("madre", "mother", "ma·dre")],
    sentence: { es: "Todo el día estoy cansado en la ciudad.", en: "All day I'm tired in the city." },
  },
  {
    id: "g",
    sound: "g",
    title: "Hard and soft G",
    summary: "G before a, o, u is like “g” in “go.” Before e and i, it becomes the j sound.",
    tip: "Gue and gui keep the hard g: guitarra (the u is silent).",
    mouth: "Between vowels the g relaxes: agua sounds soft.",
    words: [w("gato", "cat", "ga·to"), w("agua", "water", "a·gua"), w("gracias", "thank you", "gra·cias"), w("gente", "people", "gen·te"), w("guitarra", "guitar", "gui·ta·rra"), w("tengo", "I have", "ten·go")],
    sentence: { es: "Gracias, tengo agua y una guitarra.", en: "Thanks, I have water and a guitar." },
  },
  {
    id: "h-silent",
    sound: "h",
    title: "The silent H",
    summary: "H is always silent in Spanish.",
    tip: "Hola is “o-la.” But ch is its own sound, like English “ch.”",
    mouth: "Start with the vowel after the h.",
    words: [w("hola", "hello", "ho·la"), w("hambre", "hunger", "ham·bre"), w("hoy", "today", "hoy"), w("hermano", "brother", "her·ma·no"), w("hora", "hour", "ho·ra"), w("ahora", "now", "a·ho·ra")],
    sentence: { es: "Hola, hoy mi hermano tiene hambre.", en: "Hi, today my brother is hungry." },
  },
];
