// Guided roleplays. The partner's lines are scripted; the learner's replies are
// matched against key phrases (accent-insensitive) to choose the next turn.
// These run fully on-device. Open-ended conversation uses the AI provider.

import type { KeywordRequirement, Scenario, SlotOption } from "../engine/types";
import { fold } from "../engine/text";

const req = (label: string, ...anyOf: string[]): KeywordRequirement => ({ label, anyOf: anyOf.map(fold) });
const slot = (pairs: [string, string][]): SlotOption[] => pairs.map(([match, display]) => ({ match: fold(match), display }));

const DRINKS = slot([
  ["cafe con leche", "un café con leche"], ["cafe", "un café"], ["te", "un té"], ["agua", "un agua"], ["jugo", "un jugo"],
  ["zumo", "un zumo"], ["limonada", "una limonada"], ["refresco", "un refresco"], ["leche", "una leche"], ["cerveza", "una cerveza"],
]);
const DISHES = slot([
  ["pollo", "el pollo con arroz"], ["arroz", "el arroz con pollo"], ["carne", "la carne"], ["pescado", "el pescado"],
  ["ensalada", "la ensalada"], ["sopa", "la sopa"], ["pasta", "la pasta"], ["hamburguesa", "la hamburguesa"], ["pizza", "la pizza"],
]);

export const SCENARIOS: Scenario[] = [
  {
    id: "cafe",
    title: "Coffee shop",
    setting: "A small café on a busy morning.",
    role: "You're ordering something to drink.",
    partner: "Barista",
    level: 1,
    difficulty: 0.15,
    emoji: "☕",
    requiresLesson: "u1-l1",
    goals: [
      { id: "greet", label: "Greet the barista" },
      { id: "order", label: "Order a drink" },
      { id: "size", label: "Answer a follow-up question" },
      { id: "pay", label: "Pay and say thanks" },
    ],
    vocab: ["v:el-cafe", "v:el-te", "v:la-leche", "v:por-favor", "v:gracias"],
    phrases: ["Un café, por favor.", "Para llevar.", "Aquí, por favor.", "¿Cuánto es?"],
    turns: [
      {
        id: "t1",
        npc: { es: "¡Hola, buenos días! ¿Qué te pongo?", en: "Hi, good morning! What can I get you?" },
        starters: ["Hola, buenos días…", "Un café, por favor.", "Quiero un té…"],
        reprompt: { es: "Perdona, ¿qué quieres tomar? ¿Un café? ¿Un té?", en: "Sorry, what would you like to drink? A coffee? A tea?" },
        intents: [
          {
            id: "order",
            requirements: [req("drink", ...DRINKS.map((d) => d.match))],
            slot: { name: "drink", options: DRINKS },
            reply: { es: "Muy bien, {drink}.", en: "Great, {drink}." },
            next: "t2",
            goal: "order",
          },
          {
            id: "greet-only",
            requirements: [req("greeting", "hola", "buenos dias", "buenas")],
            reply: { es: "¡Hola! ¿Qué quieres tomar?", en: "Hi! What would you like to drink?" },
            next: "t1b",
            goal: "greet",
          },
        ],
      },
      {
        id: "t1b",
        npc: { es: "Tenemos café, té, jugo de naranja y limonada.", en: "We have coffee, tea, orange juice and lemonade." },
        starters: ["Un café, por favor.", "Quiero una limonada."],
        reprompt: { es: "¿Café, té, jugo o limonada?", en: "Coffee, tea, juice or lemonade?" },
        intents: [
          { id: "order", requirements: [req("drink", ...DRINKS.map((d) => d.match))], slot: { name: "drink", options: DRINKS }, reply: { es: "Perfecto, {drink}.", en: "Perfect, {drink}." }, next: "t2", goal: "order" },
        ],
      },
      {
        id: "t2",
        npc: { es: "¿Para tomar aquí o para llevar?", en: "For here or to go?" },
        starters: ["Para llevar, por favor.", "Aquí, por favor."],
        reprompt: { es: "¿Lo tomas aquí o te lo llevas?", en: "Are you having it here or taking it with you?" },
        intents: [
          { id: "togo", requirements: [req("to go", "llevar")], reply: { es: "Muy bien, para llevar.", en: "Okay, to go." }, next: "t3", goal: "size" },
          { id: "here", requirements: [req("here", "aqui", "tomar aqui")], reply: { es: "Perfecto, siéntate donde quieras.", en: "Perfect, sit wherever you like." }, next: "t3", goal: "size" },
        ],
      },
      {
        id: "t3",
        npc: { es: "Son tres dólares con cincuenta.", en: "That's three fifty." },
        starters: ["Aquí tiene.", "¿Puedo pagar con tarjeta?", "Gracias."],
        reprompt: { es: "Son tres cincuenta, por favor.", en: "Three fifty, please." },
        intents: [
          { id: "card", requirements: [req("card", "tarjeta")], reply: { es: "Claro, con tarjeta está bien.", en: "Sure, card is fine." }, next: "t4", goal: "pay" },
          { id: "pay", requirements: [req("pay", "aqui tiene", "aqui esta", "gracias", "vale", "bien", "ok", "efectivo", "tome")], reply: { es: "¡Gracias!", en: "Thank you!" }, next: "t4", goal: "pay" },
        ],
      },
      {
        id: "t4",
        npc: { es: "Aquí tienes. ¡Que tengas un buen día!", en: "Here you go. Have a good day!" },
        starters: ["Gracias, igualmente.", "Gracias, adiós."],
        reprompt: { es: "¡Que tengas un buen día!", en: "Have a good day!" },
        intents: [{ id: "bye", requirements: [req("thanks / bye", "gracias", "adios", "igualmente", "hasta luego", "chao", "chau")], next: "end" }],
      },
    ],
  },
  {
    id: "meeting",
    title: "Meeting someone new",
    setting: "A friend's party. Someone introduces themselves.",
    role: "Introduce yourself and keep the conversation going.",
    partner: "Marta",
    level: 1,
    difficulty: 0.12,
    emoji: "🤝",
    requiresLesson: "u1-l3",
    goals: [
      { id: "name", label: "Say your name" },
      { id: "origin", label: "Say where you're from" },
      { id: "ask", label: "Ask a question back" },
      { id: "feel", label: "Say how you are" },
    ],
    vocab: ["v:me-llamo", "v:soy", "v:de-donde-eres", "v:mucho-gusto"],
    phrases: ["Me llamo…", "Soy de…", "¿Y tú?", "Mucho gusto."],
    turns: [
      {
        id: "t1",
        npc: { es: "¡Hola! Me llamo Marta. ¿Cómo te llamas?", en: "Hi! My name is Marta. What's your name?" },
        starters: ["Me llamo…", "Hola, Marta, me llamo…"],
        reprompt: { es: "Perdona, ¿cómo te llamas?", en: "Sorry, what's your name?" },
        intents: [{ id: "name", requirements: [req("my name", "me llamo", "soy", "mi nombre es")], reply: { es: "¡Mucho gusto!", en: "Nice to meet you!" }, next: "t2", goal: "name" }],
      },
      {
        id: "t2",
        npc: { es: "¿De dónde eres?", en: "Where are you from?" },
        starters: ["Soy de…", "Soy de Estados Unidos."],
        reprompt: { es: "¿De qué país o ciudad eres?", en: "What country or city are you from?" },
        intents: [{ id: "origin", requirements: [req("from", "soy de", "de", "vivo en")], reply: { es: "¡Qué bien! Yo soy de Sevilla, en España.", en: "How nice! I'm from Seville, in Spain." }, next: "t3", goal: "origin" }],
      },
      {
        id: "t3",
        npc: { es: "¿Hablas mucho español?", en: "Do you speak a lot of Spanish?" },
        starters: ["Hablo un poco.", "Sí, un poco. ¿Y tú, hablas inglés?"],
        reprompt: { es: "¿Hablas español? ¿Mucho o un poco?", en: "Do you speak Spanish? A lot or a little?" },
        intents: [
          { id: "ask-back", requirements: [req("question back", "y tu", "hablas ingles", "tu hablas")], reply: { es: "Sí, hablo un poco de inglés. ¡Tu español está muy bien!", en: "Yes, I speak a little English. Your Spanish is very good!" }, next: "t4", goal: "ask" },
          { id: "answer", requirements: [req("answer", "hablo", "un poco", "si", "no", "mucho", "poco")], reply: { es: "¡Pues hablas muy bien!", en: "Well, you speak very well!" }, next: "t3b" },
        ],
      },
      {
        id: "t3b",
        npc: { es: "¿Quieres preguntarme algo?", en: "Do you want to ask me anything?" },
        starters: ["¿Y tú, hablas inglés?", "¿Cuántos años tienes?", "¿Dónde vives?"],
        reprompt: { es: "Puedes preguntarme algo: ¿dónde vivo?, ¿qué hago?…", en: "You can ask me something: where I live, what I do…" },
        intents: [{ id: "ask", requirements: [req("question", "y tu", "donde", "que", "cuantos", "como", "hablas", "tienes", "eres", "vives", "trabajas")], reply: { es: "Buena pregunta. Vivo aquí, en la ciudad, y trabajo en un hotel.", en: "Good question. I live here in the city and I work at a hotel." }, next: "t4", goal: "ask" }],
      },
      {
        id: "t4",
        npc: { es: "Oye, ¿y cómo estás? ¿Te gusta la fiesta?", en: "Hey, how are you? Are you enjoying the party?" },
        starters: ["Estoy muy bien, gracias.", "Sí, me gusta mucho."],
        reprompt: { es: "¿Estás bien? ¿Te gusta la fiesta?", en: "Are you okay? Do you like the party?" },
        intents: [{ id: "feel", requirements: [req("how you are", "estoy", "bien", "me gusta", "si", "cansado", "cansada", "contento", "contenta")], reply: { es: "¡Me alegro! Bueno, voy por algo de beber. ¡Hasta luego!", en: "Glad to hear it! Well, I'm going to get something to drink. See you later!" }, next: "end", goal: "feel" }],
      },
    ],
  },
  {
    id: "restaurant",
    title: "Restaurant",
    setting: "A neighborhood restaurant at lunchtime.",
    role: "Get a table, order food and a drink, then ask for the check.",
    partner: "Waiter",
    level: 1,
    difficulty: 0.22,
    emoji: "🍽️",
    requiresLesson: "u3-l3",
    goals: [
      { id: "table", label: "Ask for a table" },
      { id: "food", label: "Order food" },
      { id: "drink", label: "Order a drink" },
      { id: "bill", label: "Ask for the check" },
    ],
    vocab: ["v:la-mesa", "v:quisiera", "v:para-mi", "v:la-cuenta"],
    phrases: ["Una mesa para dos.", "Quisiera…", "Para mí…", "La cuenta, por favor."],
    turns: [
      {
        id: "t1",
        npc: { es: "Buenas tardes. ¿Cuántas personas?", en: "Good afternoon. How many people?" },
        starters: ["Una mesa para dos, por favor.", "Para uno."],
        reprompt: { es: "¿Mesa para cuántas personas?", en: "A table for how many people?" },
        intents: [{ id: "table", requirements: [req("number", "uno", "una", "dos", "tres", "cuatro", "cinco", "solo", "para")], reply: { es: "Perfecto. Por aquí, por favor.", en: "Perfect. This way, please." }, next: "t2", goal: "table" }],
      },
      {
        id: "t2",
        npc: { es: "Aquí tiene el menú. ¿Qué desea comer?", en: "Here's the menu. What would you like to eat?" },
        starters: ["Quisiera el pollo con arroz.", "Para mí, la ensalada."],
        reprompt: { es: "Hoy tenemos pollo con arroz, pescado, sopa y ensalada. ¿Qué le traigo?", en: "Today we have chicken with rice, fish, soup and salad. What can I bring you?" },
        intents: [{ id: "food", requirements: [req("dish", ...DISHES.map((d) => d.match))], slot: { name: "dish", options: DISHES }, reply: { es: "Muy bien, {dish}. Excelente elección.", en: "Very good, {dish}. Excellent choice." }, next: "t3", goal: "food" }],
      },
      {
        id: "t3",
        npc: { es: "¿Y para tomar?", en: "And to drink?" },
        starters: ["Un agua, por favor.", "Quisiera un jugo de naranja."],
        reprompt: { es: "¿Quiere algo de tomar? ¿Agua, jugo, un refresco?", en: "Would you like something to drink? Water, juice, a soda?" },
        intents: [
          { id: "drink", requirements: [req("drink", ...DRINKS.map((d) => d.match))], slot: { name: "drink", options: DRINKS }, reply: { es: "Perfecto, {drink}. Ahora se lo traigo.", en: "Perfect, {drink}. I'll bring it right away." }, next: "t4", goal: "drink" },
          { id: "none", requirements: [req("nothing", "nada", "no gracias")], reply: { es: "Muy bien.", en: "Very well." }, next: "t4", goal: "drink" },
        ],
      },
      {
        id: "t4",
        npc: { es: "¿Todo bien? ¿Algo más?", en: "Is everything okay? Anything else?" },
        starters: ["Nada más, gracias. La cuenta, por favor.", "Todo muy bien, gracias."],
        reprompt: { es: "¿Le traigo algo más o la cuenta?", en: "Can I bring you something else, or the check?" },
        intents: [
          { id: "bill", requirements: [req("the check", "cuenta")], reply: { es: "Enseguida. Son doscientos pesos.", en: "Right away. That's two hundred pesos." }, next: "t5", goal: "bill" },
          { id: "fine", requirements: [req("all good", "nada mas", "todo bien", "muy bien", "gracias", "no")], reply: { es: "Me alegro.", en: "Glad to hear it." }, next: "t4b" },
        ],
      },
      {
        id: "t4b",
        npc: { es: "¿Le traigo la cuenta?", en: "Shall I bring you the check?" },
        starters: ["Sí, la cuenta, por favor."],
        reprompt: { es: "¿La cuenta?", en: "The check?" },
        intents: [{ id: "bill", requirements: [req("yes / the check", "si", "cuenta", "por favor", "claro")], reply: { es: "Aquí tiene. Son doscientos pesos.", en: "Here you are. That's two hundred pesos." }, next: "t5", goal: "bill" }],
      },
      {
        id: "t5",
        npc: { es: "¿Paga con tarjeta o en efectivo?", en: "Are you paying by card or in cash?" },
        starters: ["Con tarjeta.", "En efectivo."],
        reprompt: { es: "¿Tarjeta o efectivo?", en: "Card or cash?" },
        intents: [{ id: "pay", requirements: [req("card / cash", "tarjeta", "efectivo")], reply: { es: "Perfecto. ¡Muchas gracias y buen provecho!", en: "Perfect. Thank you very much and enjoy!" }, next: "end" }],
      },
    ],
  },
  {
    id: "directions",
    title: "Asking for directions",
    setting: "A street corner in an unfamiliar city.",
    role: "Find out how to get to the museum.",
    partner: "Local resident",
    level: 1,
    difficulty: 0.25,
    emoji: "🗺️",
    requiresLesson: "u5-l2",
    goals: [
      { id: "polite", label: "Get someone's attention politely" },
      { id: "ask", label: "Ask where the museum is" },
      { id: "confirm", label: "Check you understood" },
      { id: "thank", label: "Thank them" },
    ],
    vocab: ["v:como-llego-a", "v:a-la-derecha", "v:a-la-izquierda", "v:todo-recto"],
    phrases: ["Perdón…", "¿Cómo llego al museo?", "¿Está lejos?", "¿Puede repetir?"],
    turns: [
      {
        id: "t1",
        npc: { es: "¿Sí? ¿Te puedo ayudar?", en: "Yes? Can I help you?" },
        starters: ["Sí, perdón. ¿Cómo llego al museo?", "¿Dónde está el museo?"],
        reprompt: { es: "¿Qué buscas?", en: "What are you looking for?" },
        intents: [{ id: "ask", requirements: [req("the museum", "museo")], reply: { es: "¿El museo? Sí, claro.", en: "The museum? Yes, of course." }, next: "t2", goal: "ask" }],
      },
      {
        id: "t2",
        npc: { es: "Sigue todo recto dos calles y después dobla a la izquierda. El museo está en la esquina.", en: "Go straight for two blocks and then turn left. The museum is on the corner." },
        starters: ["¿A la izquierda?", "¿Está lejos?", "¿Puede repetir, por favor?"],
        reprompt: { es: "Recto dos calles, luego a la izquierda.", en: "Straight two blocks, then left." },
        intents: [
          { id: "confirm", requirements: [req("check", "izquierda", "derecha", "recto", "dos calles", "esquina")], reply: { es: "Sí, exacto: a la izquierda, en la esquina.", en: "Yes, exactly: to the left, on the corner." }, next: "t3", goal: "confirm" },
          { id: "far", requirements: [req("is it far?", "lejos", "cerca", "minutos")], reply: { es: "No, está cerca. Unos cinco minutos a pie.", en: "No, it's close. About five minutes on foot." }, next: "t3", goal: "confirm" },
        ],
      },
      {
        id: "t3",
        npc: { es: "¿Algo más?", en: "Anything else?" },
        starters: ["No, muchas gracias.", "¿Hay una farmacia cerca?"],
        reprompt: { es: "¿Necesitas algo más?", en: "Do you need anything else?" },
        intents: [
          { id: "pharmacy", requirements: [req("another place", "farmacia", "banco", "baño", "bano", "supermercado", "hotel")], reply: { es: "Sí, hay una al lado del museo.", en: "Yes, there's one next to the museum." }, next: "t4" },
          { id: "thank", requirements: [req("thanks", "gracias", "no", "nada")], reply: { es: "¡De nada! ¡Que disfrutes el museo!", en: "You're welcome! Enjoy the museum!" }, next: "end", goal: "thank" },
        ],
      },
      {
        id: "t4",
        npc: { es: "¿Te ayudo con algo más?", en: "Can I help with anything else?" },
        starters: ["No, muchas gracias."],
        reprompt: { es: "¿Todo claro?", en: "All clear?" },
        intents: [{ id: "thank", requirements: [req("thanks", "gracias", "no", "claro", "perfecto")], reply: { es: "¡De nada! ¡Buen día!", en: "You're welcome! Have a good day!" }, next: "end", goal: "thank" }],
      },
    ],
  },
  {
    id: "market",
    title: "Market stall",
    setting: "A fruit and vegetable stall at a Saturday market.",
    role: "Buy fruit and vegetables and pay.",
    partner: "Vendor",
    level: 1,
    difficulty: 0.28,
    emoji: "🍅",
    requiresLesson: "u6-l3",
    goals: [
      { id: "buy", label: "Ask for something by weight" },
      { id: "more", label: "Add a second item" },
      { id: "price", label: "Ask the price" },
      { id: "finish", label: "Say that's all" },
    ],
    vocab: ["v:el-kilo", "v:medio", "v:me-da", "v:eso-es-todo"],
    phrases: ["¿Me da un kilo de…?", "Medio kilo de…", "¿Cuánto es?", "Eso es todo."],
    turns: [
      {
        id: "t1",
        npc: { es: "¡Buenos días! Todo muy fresco hoy. ¿Qué le doy?", en: "Good morning! Everything's very fresh today. What can I get you?" },
        starters: ["Un kilo de tomates, por favor.", "¿Me da medio kilo de naranjas?"],
        reprompt: { es: "Tengo tomates, naranjas, manzanas y aguacates. ¿Qué quiere?", en: "I have tomatoes, oranges, apples and avocados. What would you like?" },
        intents: [{ id: "buy", requirements: [req("produce", "tomate", "naranja", "manzana", "aguacate", "fruta", "kilo")], reply: { es: "Aquí tiene. ¿Algo más?", en: "Here you are. Anything else?" }, next: "t2", goal: "buy" }],
      },
      {
        id: "t2",
        npc: { es: "Las manzanas están muy buenas hoy.", en: "The apples are very good today." },
        starters: ["Medio kilo de manzanas, por favor.", "No, gracias. ¿Cuánto es?"],
        reprompt: { es: "¿Quiere algo más? ¿Manzanas?", en: "Would you like anything else? Apples?" },
        intents: [
          { id: "more", requirements: [req("another item", "manzana", "naranja", "tomate", "aguacate", "medio", "kilo", "si")], reply: { es: "Perfecto, se las pongo.", en: "Perfect, I'll add them." }, next: "t3", goal: "more" },
          { id: "price", requirements: [req("price", "cuanto", "precio")], reply: { es: "Son sesenta pesos.", en: "That's sixty pesos." }, next: "t4", goal: "price" },
        ],
      },
      {
        id: "t3",
        npc: { es: "¿Algo más, o es todo?", en: "Anything else, or is that all?" },
        starters: ["Eso es todo. ¿Cuánto es?"],
        reprompt: { es: "¿Es todo?", en: "Is that everything?" },
        intents: [
          { id: "price", requirements: [req("price", "cuanto", "precio")], reply: { es: "Son ochenta pesos en total.", en: "That's eighty pesos in total." }, next: "t4", goal: "price" },
          { id: "finish", requirements: [req("that's all", "es todo", "nada mas", "no", "ya")], reply: { es: "Muy bien. Son ochenta pesos.", en: "Very good. That's eighty pesos." }, next: "t4", goal: "finish" },
        ],
      },
      {
        id: "t4",
        npc: { es: "¿Tiene cambio?", en: "Do you have change?" },
        starters: ["Sí, aquí tiene.", "No, lo siento. Solo tengo cien."],
        reprompt: { es: "¿Tiene monedas o billetes pequeños?", en: "Do you have coins or small bills?" },
        intents: [{ id: "pay", requirements: [req("answer", "si", "no", "aqui tiene", "tengo", "cien", "lo siento", "tarjeta")], reply: { es: "No hay problema. ¡Gracias, que le vaya bien!", en: "No problem. Thanks, take care!" }, next: "end", goal: "finish" }],
      },
    ],
  },
  {
    id: "plans",
    title: "Making plans",
    setting: "A text-message style call with a friend.",
    role: "Agree on a plan for the weekend.",
    partner: "Diego",
    level: 2,
    difficulty: 0.35,
    emoji: "📅",
    requiresLesson: "u8-l1",
    goals: [
      { id: "react", label: "Respond to an invitation" },
      { id: "time", label: "Agree on a time" },
      { id: "place", label: "Decide where to meet" },
      { id: "close", label: "Close the conversation" },
    ],
    vocab: ["v:quieres-ir", "v:claro", "v:te-parece", "v:nos-vemos"],
    phrases: ["¡Claro!", "¿A qué hora?", "¿Te parece…?", "Nos vemos."],
    turns: [
      {
        id: "t1",
        npc: { es: "¡Hola! ¿Quieres ir al cine el sábado?", en: "Hi! Do you want to go to the movies on Saturday?" },
        starters: ["¡Claro! ¿A qué hora?", "Lo siento, el sábado no puedo."],
        reprompt: { es: "¿Te apetece ir al cine el sábado? ¿Sí o no?", en: "Do you feel like going to the movies on Saturday? Yes or no?" },
        intents: [
          { id: "yes", requirements: [req("yes", "claro", "si", "vale", "buena idea", "me gusta", "perfecto", "por que no")], reply: { es: "¡Genial!", en: "Great!" }, next: "t2", goal: "react" },
          { id: "no", requirements: [req("can't", "no puedo", "lo siento", "tengo que", "no")], reply: { es: "¡Qué pena! ¿Y el domingo?", en: "What a shame! How about Sunday?" }, next: "t1b", goal: "react" },
        ],
      },
      {
        id: "t1b",
        npc: { es: "¿Puedes el domingo por la tarde?", en: "Can you do Sunday afternoon?" },
        starters: ["Sí, el domingo sí puedo.", "El domingo está bien."],
        reprompt: { es: "¿El domingo te va bien?", en: "Does Sunday work for you?" },
        intents: [{ id: "yes", requirements: [req("yes", "si", "claro", "puedo", "bien", "vale", "perfecto")], reply: { es: "¡Perfecto!", en: "Perfect!" }, next: "t2" }],
      },
      {
        id: "t2",
        npc: { es: "La película empieza a las siete y a las nueve. ¿Qué prefieres?", en: "The movie starts at seven and at nine. Which do you prefer?" },
        starters: ["Prefiero a las siete.", "¿Te parece bien a las nueve?"],
        reprompt: { es: "¿A las siete o a las nueve?", en: "At seven or at nine?" },
        intents: [{ id: "time", requirements: [req("a time", "siete", "nueve", "7", "9", "temprano", "tarde")], reply: { es: "Vale, compro las entradas.", en: "Okay, I'll buy the tickets." }, next: "t3", goal: "time" }],
      },
      {
        id: "t3",
        npc: { es: "¿Dónde nos vemos? ¿En el cine o antes en un café?", en: "Where shall we meet? At the movie theater or before at a café?" },
        starters: ["Nos vemos en el cine.", "En el café, ¿te parece?"],
        reprompt: { es: "¿En el cine o en el café?", en: "At the theater or at the café?" },
        intents: [{ id: "place", requirements: [req("a place", "cine", "cafe", "casa", "parque", "estacion", "metro")], reply: { es: "¡Perfecto, allí nos vemos!", en: "Perfect, see you there!" }, next: "t4", goal: "place" }],
      },
      {
        id: "t4",
        npc: { es: "¡Qué bien! Tengo muchas ganas.", en: "Great! I'm really looking forward to it." },
        starters: ["¡Yo también! Nos vemos el sábado.", "¡Hasta el sábado!"],
        reprompt: { es: "¡Hasta pronto!", en: "See you soon!" },
        intents: [{ id: "close", requirements: [req("goodbye", "nos vemos", "hasta", "adios", "chao", "chau", "yo tambien", "gracias", "genial")], next: "end", goal: "close" }],
      },
    ],
  },
  {
    id: "hotel",
    title: "Hotel check-in",
    setting: "The front desk of a hotel, late in the evening.",
    role: "Check in, ask about breakfast and Wi-Fi.",
    partner: "Receptionist",
    level: 2,
    difficulty: 0.38,
    emoji: "🏨",
    requiresLesson: "u12-l1",
    goals: [
      { id: "reservation", label: "Give your reservation name" },
      { id: "nights", label: "Say how many nights" },
      { id: "breakfast", label: "Ask about breakfast" },
      { id: "wifi", label: "Ask about the Wi-Fi" },
    ],
    vocab: ["v:la-habitacion", "v:reservar", "v:el-pasaporte"],
    phrases: ["Tengo una reserva a nombre de…", "¿A qué hora es el desayuno?", "¿Hay wifi?"],
    turns: [
      {
        id: "t1",
        npc: { es: "Buenas noches, bienvenido. ¿Tiene una reserva?", en: "Good evening, welcome. Do you have a reservation?" },
        starters: ["Sí, a nombre de…", "Sí, tengo una reserva."],
        reprompt: { es: "¿A nombre de quién está la reserva?", en: "What name is the reservation under?" },
        intents: [{ id: "res", requirements: [req("reservation", "reserva", "nombre", "si", "me llamo", "soy")], reply: { es: "Perfecto, aquí está. ¿Me deja su pasaporte, por favor?", en: "Perfect, here it is. May I have your passport, please?" }, next: "t2", goal: "reservation" }],
      },
      {
        id: "t2",
        npc: { es: "Gracias. ¿Cuántas noches se queda?", en: "Thank you. How many nights are you staying?" },
        starters: ["Tres noches.", "Me quedo dos noches."],
        reprompt: { es: "¿Una noche, dos, tres…?", en: "One night, two, three…?" },
        intents: [{ id: "nights", requirements: [req("number of nights", "una", "dos", "tres", "cuatro", "cinco", "semana", "noche", "noches")], reply: { es: "Muy bien. Su habitación es la 204, en el segundo piso.", en: "Very good. Your room is 204, on the second floor." }, next: "t3", goal: "nights" }],
      },
      {
        id: "t3",
        npc: { es: "¿Tiene alguna pregunta?", en: "Do you have any questions?" },
        starters: ["¿A qué hora es el desayuno?", "¿Hay wifi?"],
        reprompt: { es: "Puede preguntarme por el desayuno, el wifi…", en: "You can ask me about breakfast, the Wi-Fi…" },
        intents: [
          { id: "breakfast", requirements: [req("breakfast", "desayuno", "desayunar")], reply: { es: "El desayuno es de siete a diez, en el restaurante.", en: "Breakfast is from seven to ten, in the restaurant." }, next: "t4", goal: "breakfast" },
          { id: "wifi", requirements: [req("wifi", "wifi", "internet", "contrasena", "clave")], reply: { es: "Sí, la contraseña está en la tarjeta de la habitación.", en: "Yes, the password is on the room card." }, next: "t4b", goal: "wifi" },
        ],
      },
      {
        id: "t4",
        npc: { es: "¿Algo más?", en: "Anything else?" },
        starters: ["¿Hay wifi en la habitación?", "No, gracias."],
        reprompt: { es: "¿Necesita algo más?", en: "Do you need anything else?" },
        intents: [
          { id: "wifi", requirements: [req("wifi", "wifi", "internet", "contrasena", "clave")], reply: { es: "Sí, la contraseña está en la tarjeta de la habitación.", en: "Yes, the password is on the room card." }, next: "t5", goal: "wifi" },
          { id: "done", requirements: [req("that's all", "no", "gracias", "nada")], reply: { es: "Perfecto.", en: "Perfect." }, next: "t5" },
        ],
      },
      {
        id: "t4b",
        npc: { es: "¿Algo más?", en: "Anything else?" },
        starters: ["¿A qué hora es el desayuno?", "No, gracias."],
        reprompt: { es: "¿Necesita algo más?", en: "Do you need anything else?" },
        intents: [
          { id: "breakfast", requirements: [req("breakfast", "desayuno", "desayunar")], reply: { es: "El desayuno es de siete a diez, en el restaurante.", en: "Breakfast is from seven to ten, in the restaurant." }, next: "t5", goal: "breakfast" },
          { id: "done", requirements: [req("that's all", "no", "gracias", "nada")], reply: { es: "Perfecto.", en: "Perfect." }, next: "t5" },
        ],
      },
      {
        id: "t5",
        npc: { es: "Aquí tiene su llave. ¡Que descanse!", en: "Here's your key. Have a good rest!" },
        starters: ["Muchas gracias, buenas noches."],
        reprompt: { es: "¡Buenas noches!", en: "Good night!" },
        intents: [{ id: "bye", requirements: [req("thanks", "gracias", "buenas noches", "adios", "hasta")], next: "end" }],
      },
    ],
  },
  {
    id: "weekend",
    title: "Talking about the weekend",
    setting: "Monday morning with a coworker.",
    role: "Tell a coworker what you did on the weekend.",
    partner: "Lucía",
    level: 2,
    difficulty: 0.42,
    emoji: "🏖️",
    requiresLesson: "u7-l2",
    goals: [
      { id: "activity", label: "Say what you did (past tense)" },
      { id: "detail", label: "Add a detail: who or where" },
      { id: "opinion", label: "Say how it was" },
      { id: "ask", label: "Ask about their weekend" },
    ],
    vocab: ["v:fui", "v:hice", "v:comi", "v:vi"],
    phrases: ["Fui a…", "Fue muy divertido.", "¿Y tú, qué hiciste?"],
    turns: [
      {
        id: "t1",
        npc: { es: "¡Buenos días! ¿Qué tal el fin de semana? ¿Qué hiciste?", en: "Good morning! How was the weekend? What did you do?" },
        starters: ["Fui a la playa.", "Vi una película.", "Salí con mis amigos."],
        reprompt: { es: "¿Hiciste algo especial? ¿Fuiste a algún sitio?", en: "Did you do anything special? Did you go anywhere?" },
        intents: [{ id: "activity", requirements: [req("past action", "fui", "hice", "vi", "comi", "sali", "trabaje", "estudie", "visite", "jugue", "cocine", "descanse", "lei", "estuve", "hable", "cene", "bebi")], reply: { es: "¡Qué bien!", en: "How nice!" }, next: "t2", goal: "activity" }],
      },
      {
        id: "t2",
        npc: { es: "¿Con quién? ¿O fuiste solo?", en: "With whom? Or did you go alone?" },
        starters: ["Con mis amigos.", "Con mi familia.", "Solo."],
        reprompt: { es: "¿Estuviste con alguien?", en: "Were you with anyone?" },
        intents: [{ id: "detail", requirements: [req("who", "con", "solo", "sola", "amigo", "amiga", "familia", "hermano", "hermana", "novio", "novia")], reply: { es: "Ah, qué bien.", en: "Oh, nice." }, next: "t3", goal: "detail" }],
      },
      {
        id: "t3",
        npc: { es: "¿Y qué tal? ¿Te gustó?", en: "And how was it? Did you like it?" },
        starters: ["Sí, fue muy divertido.", "Me gustó mucho.", "Fue un poco aburrido."],
        reprompt: { es: "¿Fue divertido o aburrido?", en: "Was it fun or boring?" },
        intents: [{ id: "opinion", requirements: [req("how it was", "fue", "me gusto", "divertido", "aburrido", "bien", "genial", "increible", "interesante", "si", "no")], reply: { es: "¡Me alegro mucho!", en: "I'm really glad!" }, next: "t4", goal: "opinion" }],
      },
      {
        id: "t4",
        npc: { es: "Bueno, ¡a trabajar!", en: "Well, time to work!" },
        starters: ["¿Y tú? ¿Qué hiciste?"],
        reprompt: { es: "Uf, tengo mucho trabajo hoy.", en: "Phew, I have a lot of work today." },
        intents: [
          { id: "ask", requirements: [req("ask back", "y tu", "que hiciste", "tu fin de semana", "que tal")], reply: { es: "Yo fui a casa de mis padres y comí muchísimo. ¡Hasta luego!", en: "I went to my parents' house and ate way too much. See you later!" }, next: "end", goal: "ask" },
          { id: "bye", requirements: [req("goodbye", "hasta luego", "adios", "si", "vale", "claro")], reply: { es: "¡Hasta luego!", en: "See you later!" }, next: "end" },
        ],
      },
    ],
  },
];

/** Phrases the partner understands in any scenario — this is where the phrase bank pays off. */
export const REPAIR_INTENTS = {
  repeat: ["repetir", "repitelo", "repite", "otra vez", "no entiendo", "no entendi", "como", "perdon", "que dijiste", "puede repetir", "puedes repetir"],
  slower: ["mas despacio", "despacio", "mas lento"],
  howSay: ["como se dice"],
};
